codes/go/chapter_searching/linear_search.go, codes/go/chapter_searching/linear_search_test.go, codes/go/chapter_tree/binary_search_tree.go, codes/go/chapter_tree/binary_tree.go, codes/go/chapter_tree/binary_tree_test.go, codes/go/pkg/list_node.go, codes/go/pkg/list_node_test.go, codes/go/pkg/tree_node.go, codes/go/pkg/tree_node_test.go
=> feat(go): support basic pkg

codes/javascript/chapter_array_and_linkedlist/array.js, docs/chapter_array_and_linkedlist/array.md
=> add javascript codes for Array

codes/javascript/chapter_sorting/bubble_sort.js, codes/javascript/chapter_sorting/insertion_sort.js, codes/javascript/chapter_sorting/merge_sort.js, codes/javascript/chapter_sorting/quick_sort.js, docs/chapter_sorting/bubble_sort.md, docs/chapter_sorting/insertion_sort.md, docs/chapter_sorting/merge_sort.md, docs/chapter_sorting/quick_sort.md
=> add sort for javascript codes

codes/typescript/chapter_array_and_linkedlist/array.ts, docs/chapter_array_and_linkedlist/array.md
=> Add TypeScript code and docs for Chapter of Array

codes/go/chapter_sorting/bubble_sort/bubble_sort.go, codes/go/chapter_sorting/bubble_sort/bubble_sort_test.go, docs/chapter_sorting/bubble_sort.md
=> Bubble sort using go

codes/javascript/chapter_tree/binary_search_tree.js, codes/javascript/chapter_tree/binary_tree.js, codes/javascript/chapter_tree/binary_tree_bfs.js, codes/javascript/chapter_tree/binary_tree_dfs.js, codes/javascript/include/PrintUtil.js, codes/javascript/include/TreeNode.js, docs/chapter_tree/binary_tree.md
PrintUtil.js:
console.log(p.str) will print a new empty line, which will affect the tree print.
so we should change to process.stdout.write(p.str) because it will not print an empty line.
=> Fix the PrintUtil.js showTrunks and Update JavaScript and docs' style (Chapter of Tree)

codes/c#/chapter_array_and_linkedlist/Array.cs, docs/chapter_array_and_linkedlist/array.md
Add the C# code to docs(chapter of array)
=> Add C# code to array doc

codes/typescript/chapter_tree/binary_search_tree.ts, codes/typescript/chapter_tree/binary_tree.ts, codes/typescript/chapter_tree/binary_tree_bfs.ts, codes/typescript/chapter_tree/binary_tree_dfs.ts, codes/typescript/module/PrintUtil.ts, codes/typescript/module/TreeNode.ts, docs/chapter_tree/binary_search_tree.md, docs/chapter_tree/binary_tree.md
I am sorry, I forget to create a dev branch. Is that ok? If some wrong happens, please let me know.
=> Add the TypeScript code and docs for Chapter of Tree 

codes/cpp/chapter_stack_and_queue/array_stack.cpp, codes/java/chapter_stack_and_queue/array_stack.java, codes/java/chapter_stack_and_queue/linkedlist_queue.java, codes/java/chapter_stack_and_queue/linkedlist_stack.java, codes/javascript/chapter_stack_and_queue/array_stack.js, codes/python/chapter_stack_and_queue/array_stack.py, codes/typescript/chapter_stack_and_queue/array_stack.ts, docs/chapter_stack_and_queue/queue.md, docs/chapter_stack_and_queue/stack.md
> Tip: If this PR is not related to the coding or code translation, please ignore the checklist.
=> Update array stack

docs/chapter_data_structure/data_and_memory.md
> Tip: If this PR is not related to the coding or code translation, please ignore the checklist.
=> add initialization of C++ arrays

docs/chapter_data_structure/data_and_memory.md
=> 使用多种「基本数据类型」来初始化「数组」的 C 语言版本

docs/chapter_tree/binary_tree.md
=> docs(chapter_tree/binary_tree/二叉树表示方式 *): JS code

docs/chapter_tree/binary_tree.md
=> docs(chapter_tree/binary_tree/二叉树表示方式 *): TS code

codes/swift/chapter_computational_complexity/time_complexity.swift, codes/swift/chapter_computational_complexity/worst_best_time_complexity.swift, docs/chapter_computational_complexity/time_complexity.md, docs/chapter_preface/installation.md
=> feat: add Swift codes for time complexity article

codes/csharp/chapter_stack_and_queue/deque.cs
以 C# 内置的双向队列 LinkedList 为基础，编写了 C# 版本的 deque
=> 添加 deque.cs

docs/chapter_stack_and_queue/deque.md
=> 添加 C# 内置的双向队列示例

codes/zig/chapter_computational_complexity/time_complexity.zig, codes/zig/chapter_computational_complexity/worst_best_time_complexity.zig
=> add zig code for chapter_computational_complexity (Zig Version 0.10.0)

codes/swift/Package.swift, codes/swift/chapter_computational_complexity/leetcode_two_sum.swift, docs/chapter_computational_complexity/space_time_tradeoff.md
=> feat: add Swift codes for space time tradeoff article

docs/chapter_data_structure/data_and_memory.md
=> feat: add Swift codes for data_and_memory article

codes/swift/Package.swift, codes/swift/chapter_array_and_linkedlist/array.swift, docs/chapter_array_and_linkedlist/array.md
=> feat: add Swift codes for array article

codes/go/chapter_tree/avl_tree.go, codes/go/chapter_tree/avl_tree_test.go, codes/go/pkg/tree_node.go, docs/chapter_tree/avl_tree.md
Add go code and docs of avl_tree in chapter_tree
---
=> feat(tree/avl_tree): add go code

codes/swift/Package.swift, codes/swift/chapter_array_and_linkedlist/linked_list.swift, codes/swift/chapter_computational_complexity/space_complexity.swift, codes/swift/chapter_computational_complexity/time_complexity.swift, codes/swift/chapter_computational_complexity/worst_best_time_complexity.swift, codes/swift/utils/PrintUtil.swift, docs/chapter_array_and_linkedlist/array.md, docs/chapter_array_and_linkedlist/linked_list.md, docs/chapter_computational_complexity/space_complexity.md, docs/chapter_computational_complexity/time_complexity.md, docs/chapter_data_structure/data_and_memory.md
=> feat: add Swift codes for linked_list article

codes/zig/.gitignore, codes/zig/build.zig, codes/zig/chapter_computational_complexity/leetcode_two_sum.zig, codes/zig/chapter_computational_complexity/worst_best_time_complexity.zig, codes/zig/include/PrintUtil.zig, codes/zig/include/include.zig
=> (PR #217)update a .gitignore file in the codes/zig dir

codes/go/chapter_array_and_linkedlist/my_list.go, codes/go/chapter_computational_complexity/space_complexity.go, codes/go/chapter_hashing/array_hash_map.go, codes/go/chapter_searching/hashing_search_test.go, codes/go/chapter_sorting/merge_sort.go, codes/go/chapter_sorting/quick_sort.go, codes/go/chapter_sorting/quick_sort_test.go, codes/go/chapter_stack_and_queue/array_queue.go, codes/go/chapter_stack_and_queue/array_stack.go, codes/go/chapter_stack_and_queue/deque_test.go, codes/go/chapter_stack_and_queue/linkedlist_deque.go, codes/go/chapter_stack_and_queue/linkedlist_queue.go, codes/go/chapter_stack_and_queue/linkedlist_stack.go, codes/go/chapter_stack_and_queue/queue_test.go, codes/go/chapter_stack_and_queue/stack_test.go, codes/go/chapter_tree/binary_search_tree.go, codes/go/chapter_tree/binary_search_tree_test.go, codes/go/chapter_tree/binary_tree_bfs_test.go, codes/go/chapter_tree/binary_tree_dfs_test.go, codes/go/pkg/print_utils.go, codes/go/pkg/tree_node.go, codes/go/pkg/tree_node_test.go, docs/chapter_array_and_linkedlist/list.md, docs/chapter_computational_complexity/space_complexity.md, docs/chapter_hashing/hash_map.md, docs/chapter_sorting/merge_sort.md, docs/chapter_sorting/quick_sort.md, docs/chapter_stack_and_queue/queue.md, docs/chapter_stack_and_queue/stack.md, docs/chapter_tree/binary_search_tree.md
1. Fix ArrToTree in go code.
2. In case misuse, make the classes and methods in the package private.
3. Modify docs related to the above contents.
---
=> style(go): fix go code style

codes/swift/Package.swift, codes/swift/chapter_array_and_linkedlist/list.swift, codes/swift/chapter_array_and_linkedlist/my_list.swift, codes/swift/chapter_computational_complexity/time_complexity.swift, docs/chapter_array_and_linkedlist/list.md, docs/chapter_computational_complexity/time_complexity.md
=> feat: add Swift codes for list article

codes/swift/Package.swift, codes/swift/chapter_stack_and_queue/array_stack.swift, codes/swift/chapter_stack_and_queue/linkedlist_stack.swift, codes/swift/chapter_stack_and_queue/stack.swift, docs/chapter_stack_and_queue/stack.md
=> feat: add Swift codes for stack article

codes/c/chapter_computational_complexity/time_complexity.c, codes/zig/build.zig, codes/zig/chapter_computational_complexity/leetcode_two_sum.zig, codes/zig/chapter_computational_complexity/space_complexity.zig, codes/zig/chapter_computational_complexity/time_complexity.zig, codes/zig/chapter_computational_complexity/worst_best_time_complexity.zig, codes/zig/include/ListNode.zig, codes/zig/include/PrintUtil.zig, codes/zig/include/TreeNode.zig, codes/zig/include/include.zig
=> add zig codes for Section 'Space Complexity' and 'Space Time Tradeoff'

codes/rust/chapter_computational_complexity/time_complexity.rs, docs/chapter_computational_complexity/time_complexity.md, docs/chapter_preface/installation.md
=> Add rust environment, and time_complexity.md rust code

codes/cpp/include/include.hpp
=> fix(codes/cpp): fix worst_best_time_complexity.cpp compile error.

Dockerfile, README.md, docker-compose.yml, docs/chapter_preface/contribution.md
This PR is not related to coding or code translation. This PR solves #134.
=> feat: update Dockerfile to deploy

codes/zig/build.zig, codes/zig/chapter_array_and_linkedlist/array.zig, codes/zig/chapter_array_and_linkedlist/linked_list.zig, codes/zig/chapter_array_and_linkedlist/list.zig, codes/zig/chapter_array_and_linkedlist/my_list.zig, codes/zig/include/PrintUtil.zig
=> add zig codes for Section 'Array', 'LinkedList' and  'List'

codes/zig/build.zig, codes/zig/chapter_sorting/bubble_sort.zig, codes/zig/chapter_sorting/insertion_sort.zig, codes/zig/chapter_stack_and_queue/array_stack.zig, codes/zig/chapter_stack_and_queue/linkedlist_stack.zig, codes/zig/chapter_stack_and_queue/stack.zig
=> add zig codes for Section 'Stack', 'Bubble Sort' and 'Insertion Sort'

codes/swift/Package.swift, codes/swift/chapter_stack_and_queue/deque.swift, codes/swift/chapter_stack_and_queue/queue.swift, docs/chapter_stack_and_queue/deque.md, docs/chapter_stack_and_queue/queue.md
=> feat: add Swift codes for deque article

codes/go/chapter_heap/my_heap.go, docs/chapter_heap/heap.md
=> fix: polling from an empty heap will cause panic

docs/chapter_sorting/quick_sort.md
Fix the Golang code for median
=> fix the Golang code for median in quick_sort.md

codes/zig/build.zig, codes/zig/chapter_heap/my_heap.zig
=> add zig codes for Section 'Heap' (my_heap.zig)

codes/swift/Package.swift, codes/swift/chapter_hashing/array_hash_map.swift, codes/swift/chapter_hashing/hash_map.swift, codes/swift/utils/PrintUtil.swift, docs/chapter_hashing/hash_map.md
=> feat: add Swift codes for hash_map article

codes/go/chapter_sorting/radix_sort.go, codes/go/chapter_sorting/radix_sort_test.go
=> Add radix_sort to go codes

codes/c/chapter_sorting/CMakeLists.txt, codes/c/chapter_sorting/quick_sort.c, codes/c/chapter_sorting/radix_sort.c
=> Add quick_sort/radix_sort to C code.

codes/zig/build.zig, codes/zig/chapter_hashing/array_hash_map.zig
=> update zig codes for Section 'Hash Map' (array_hash_map.zig)

codes/swift/Package.swift, codes/swift/chapter_tree/binary_tree.swift, docs/chapter_tree/binary_tree.md
=> feat: add Swift codes for binary_tree article

codes/swift/Package.swift, codes/swift/chapter_tree/binary_tree_bfs.swift, codes/swift/chapter_tree/binary_tree_dfs.swift, codes/swift/utils/TreeNode.swift, docs/chapter_tree/binary_tree_traversal.md
=> feat: add Swift codes for binary_tree_traversal article

mkdocs.yml
=> Remove offline plugin

codes/zig/build.zig, codes/zig/chapter_sorting/merge_sort.zig, codes/zig/chapter_sorting/quick_sort.zig, codes/zig/chapter_sorting/radix_sort.zig
add zig codes for Section 'Quick Sort' (quick_sort.zig), 'Merge Sort' (merge_sort.zig), 'Radix Sort' (radix_sort.zig)
=> add zig codes for Section Quick Sort, Merge Sort, Radix Sort

codes/zig/build.zig, codes/zig/chapter_tree/binary_tree_bfs.zig
=> add zig codes for Section 'Binary Tree'

codes/swift/Package.swift, codes/swift/chapter_tree/binary_search_tree.swift, docs/chapter_tree/binary_search_tree.md
=> feat: add Swift codes for binary_search_tree article

codes/python/chapter_stack_and_queue/linkedlist_queue.py, docs/chapter_stack_and_queue/queue.md
self.__front 初始化为 None, 元素入队判断队列是否为空，延用头节点的初始化值 None 而不是 0
=> 更新队列的链表实现中 self.__front 判空的方式

codes/zig/build.zig, codes/zig/chapter_tree/avl_tree.zig, codes/zig/chapter_tree/binary_search_tree.zig, codes/zig/chapter_tree/binary_tree_bfs.zig, codes/zig/chapter_tree/binary_tree_dfs.zig, codes/zig/include/TreeNode.zig
=> add zig codes for Section Binary Tree, Binary Search Tree and AVL Tree

codes/swift/Package.swift, codes/swift/chapter_tree/avl_tree.swift, docs/chapter_tree/avl_tree.md
=> feat: add Swift codes for avl_tree article

codes/c/chapter_array_and_linkedlist/linked_list.c, codes/c/chapter_array_and_linkedlist/my_list.c, codes/c/chapter_stack_and_queue/array_stack.c, codes/c/chapter_stack_and_queue/linkedlist_stack.c
=> fix(codes/c): Fix file header error message

codes/c/chapter_array_and_linkedlist/my_list.c, codes/c/chapter_computational_complexity/CMakeLists.txt, codes/c/chapter_computational_complexity/leetcode_two_sum.c, codes/c/chapter_sorting/quick_sort.c, codes/c/chapter_stack_and_queue/array_stack.c, codes/c/chapter_stack_and_queue/linkedlist_stack.c, codes/c/include/CMakeLists.txt, codes/c/include/include.h, codes/c/include/uthash.h
=> Modify the code style of C 

codes/rust/Cargo.lock, codes/rust/Cargo.toml, codes/rust/chapter_array_and_linkedlist/Cargo.toml, codes/rust/chapter_array_and_linkedlist/array.rs, codes/rust/chapter_array_and_linkedlist/list.rs
=> add Rust code array, list

codes/swift/Package.swift, codes/swift/chapter_heap/my_heap.swift, codes/swift/utils/PrintUtil.swift, docs/chapter_heap/heap.md
=> feat: add Swift codes for heap article

docs/chapter_preface/installation.md
=> Add c/cpp code running and debugging tutorial under windows

codes/zig/build.zig, codes/zig/chapter_array_and_linkedlist/my_list.zig, codes/zig/chapter_stack_and_queue/array_queue.zig
=> fix bug for commit 5eae708

codes/swift/chapter_stack_and_queue/array_queue.swift, docs/chapter_stack_and_queue/queue.md
=> fix: resolve build error for commit 5eae708

codes/javascript/chapter_stack_and_queue/array_queue.js, codes/typescript/chapter_stack_and_queue/array_queue.ts, docs/chapter_stack_and_queue/queue.md
=> Fix bug before commit 5eae708

codes/c/.gitignore, codes/go/chapter_graph/graph_adjacency_list.go, codes/go/chapter_graph/graph_adjacency_list_test.go, codes/go/chapter_graph/graph_adjacency_matrix.go, codes/go/chapter_graph/graph_adjacency_matrix_test.go, docs/chapter_graph/graph_operations.md
=> feat(graph): add go codes

codes/rust/chapter_array_and_linkedlist/array.rs, codes/zig/chapter_array_and_linkedlist/array.zig, codes/zig/chapter_array_and_linkedlist/linked_list.zig, codes/zig/chapter_array_and_linkedlist/list.zig, codes/zig/chapter_array_and_linkedlist/my_list.zig, codes/zig/chapter_computational_complexity/space_complexity.zig, codes/zig/chapter_hashing/array_hash_map.zig, codes/zig/chapter_hashing/hash_map.zig, codes/zig/chapter_heap/heap.zig, codes/zig/chapter_heap/my_heap.zig, codes/zig/chapter_searching/linear_search.zig, codes/zig/chapter_sorting/bubble_sort.zig, codes/zig/chapter_sorting/insertion_sort.zig, codes/zig/chapter_stack_and_queue/array_queue.zig, codes/zig/chapter_stack_and_queue/array_stack.zig, codes/zig/chapter_stack_and_queue/deque.zig, codes/zig/chapter_stack_and_queue/linkedlist_deque.zig, codes/zig/chapter_stack_and_queue/linkedlist_queue.zig, codes/zig/chapter_stack_and_queue/linkedlist_stack.zig, codes/zig/chapter_stack_and_queue/queue.zig, codes/zig/chapter_stack_and_queue/stack.zig, codes/zig/chapter_tree/binary_tree.zig, codes/zig/chapter_tree/binary_tree_bfs.zig, codes/zig/include/ListNode.zig, codes/zig/include/PrintUtil.zig, codes/zig/include/TreeNode.zig
=> Update the coding style for Zig

codes/javascript/chapter_computational_complexity/worst_best_time_complexity.js, codes/typescript/chapter_computational_complexity/worst_best_time_complexity.ts, codes/typescript/chapter_searching/linear_search.ts, codes/typescript/chapter_tree/avl_tree.ts, codes/typescript/module/ListNode.ts, codes/typescript/module/TreeNode.ts, docs/chapter_computational_complexity/time_complexity.md, docs/chapter_tree/avl_tree.md
=> Add TypeScript code and docs to AVL tree and the coding style for Typescript and JavaScript

codes/java/chapter_graph/graph_adjacency_list.java, codes/javascript/chapter_graph/graph_adjacency_list.js, codes/typescript/chapter_graph/graph_adjacency_list.ts
=> Add JavaScript and TypeScript code for section graph adjacency list

codes/c/chapter_array_and_linkedlist/array.c, docs/chapter_array_and_linkedlist/array.md
=> feat: add array C docs

codes/cpp/chapter_heap/my_heap.cpp
Fix the problems mentioned in the PR https://github.com/krahets/hello-algo/pull/321
=> fix the function poll() in my_heap.cpp

codes/cpp/chapter_graph/graph_adjacency_list.cpp, codes/cpp/chapter_graph/graph_adjacency_matrix.cpp, docs/chapter_graph/graph_operations.md, docs/utils/extract_code_go.py
=> Add graph c++ code

codes/rust/Cargo.toml, codes/rust/chapter_sorting/insertion_sort.rs, codes/rust/chapter_sorting/merge_sort.rs, codes/rust/chapter_sorting/quick_sort.rs
=> ✨ feat(rust/sorting) add insertion, merge, quick sort code 

codes/c/chapter_sorting/bubble_sort.c, codes/csharp/chapter_sorting/bubble_sort.cs, codes/dart/chapter_sorting/bubble_sort.dart, codes/dart/chapter_sorting/insertion_sort.dart, codes/dart/chapter_sorting/merge_sort.dart, codes/dart/chapter_sorting/quick_sort.dart, codes/dart/chapter_sorting/radix_sort.dart, codes/java/chapter_sorting/bubble_sort.java
bubble_sort.dart
```
冒泡排序完成后 nums = [1, 1, 2, 3, 4, 5]
冒泡排序完成后 nums1 = [1, 1, 2, 3, 4, 5]
```
insertion_sort.dart
```
插入排序完成后 nums = [1, 1, 2, 3, 4, 5]
```
merge_sort.dart
```
归并排序完成后 nums = [0, 1, 2, 3, 4, 5, 6, 7]
```
quick_sort.dart
```
快速排序完成后 nums = [0, 1, 2, 3, 4, 5]
快速排序（中位基准数优化）完成后 nums1 = [0, 1, 2, 3, 4, 5]
快速排序（尾递归优化）完成后 nums2 = [0, 1, 2, 3, 4, 5]
```
radix_sort.dart
```
基数排序完成后 nums = [3, 4, 12, 23, 192, 788]
```
Seems you haven't add dart into the doc so I only translate the code.
=> add chapter_sorting by dart

codes/swift/Package.swift, codes/swift/chapter_graph/graph_adjacency_list.swift, codes/swift/utils/Vertex.swift
=> refactor: extract Vertex and use Array<Vertex>

codes/swift/Package.swift, codes/swift/chapter_graph/graph_adjacency_list.swift, codes/swift/chapter_graph/graph_adjacency_list_target.swift, codes/swift/chapter_graph/graph_bfs.swift, codes/swift/chapter_graph/graph_dfs.swift, codes/swift/utils/Vertex.swift, docs/chapter_graph/graph_traversal.md
=> feat: add Swift codes for graph_traversal article

docs/chapter_heap/heap.md
=> fix: Update heap.md

codes/java/include/Vertex.java, codes/python/chapter_graph/graph_adjacency_list.py, codes/python/chapter_graph/graph_adjacency_matrix.py, codes/python/chapter_graph/graph_bfs.py, codes/python/chapter_graph/graph_dfs.py, codes/python/chapter_heap/heap.py, codes/python/chapter_heap/my_heap.py, codes/python/include/__init__.py, codes/python/include/print_util.py, codes/python/include/vertex.py
=> Add the Python codes for the chapter of Graph and Heap

codes/rust/Cargo.toml, codes/rust/chapter_hashing/array_hash_map.rs
=> ✨ feat(rust/hashing): add array_hash_map

codes/javascript/chapter_graph/graph_bfs.js, codes/javascript/chapter_graph/graph_dfs.js, codes/typescript/chapter_graph/graph_bfs.ts, codes/typescript/chapter_graph/graph_dfs.ts
=> Update: Use function declarations instead of function expressions.

codes/java/chapter_graph/graph_dfs.java, codes/python/chapter_graph/graph_dfs.py
=> Fix: update the code comment

.gitignore, codes/c/.gitignore, codes/go/chapter_graph/graph_adjacency_list.go, codes/go/chapter_graph/graph_adjacency_list_test.go, codes/go/chapter_graph/graph_bfs.go, codes/go/chapter_graph/graph_bfs_test.go, codes/go/chapter_graph/graph_dfs.go, codes/go/chapter_graph/graph_dfs_test.go, codes/go/pkg/vertex.go
=> feat(go/graph): add go code for graph_dfs/bfs

docs/chapter_array_and_linkedlist/linked_list.md
=> Add linked list structure definition C language code in "linked_list. md"

codes/cpp/chapter_stack_and_queue/array_deque.cpp, codes/cpp/chapter_stack_and_queue/linkedlist_deque.cpp, codes/go/chapter_stack_and_queue/linkedlist_deque.go, codes/java/chapter_stack_and_queue/linkedlist_deque.java
=> feat: Add C++ code for the linkedlist deque and array deque

codes/javascript/chapter_stack_and_queue/array_deque.js, codes/typescript/chapter_stack_and_queue/array_deque.ts, docs/chapter_array_and_linkedlist/linked_list.md
=> feat: add array_deque for JS and TS

codes/rust/Cargo.toml, codes/rust/chapter_hashing/array_hash_map.rs, codes/rust/chapter_tree/binary_tree.rs, codes/rust/include/include.rs, codes/rust/include/print_util.rs, codes/rust/include/tree_node.rs
=> ✨ feat(rust/tree): add binary_tree

codes/csharp/chapter_graph/graph_adjacency_list.cs, codes/csharp/chapter_graph/graph_bfs.cs, codes/csharp/chapter_graph/graph_dfs.cs
add csharp code graph_bfs and graph_dfs, modify graph adjacency list class inaccessable
=> feature: Add csharp code graph_bfs and graph_dfs

codes/csharp/chapter_stack_and_queue/array_deque.cs, codes/csharp/chapter_stack_and_queue/linkedlist_deque.cs
linkedlist_deque测试结果
array_deque测试结果
=> feature: Add csharp code array_deque and linkedlist_deque

README.md, codes/rust/Cargo.toml, codes/rust/chapter_array_and_linkedlist/linked_list.rs, codes/rust/chapter_array_and_linkedlist/my_list.rs, codes/rust/include/include.rs, codes/rust/include/list_node.rs, codes/rust/include/print_util.rs, codes/zig/chapter_array_and_linkedlist/my_list.zig
=> feat: add rust codes for linked_list and my_list

codes/rust/Cargo.toml, codes/rust/chapter_computational_complexity/space_complexity.rs, codes/rust/include/include.rs
=> 🚀feat: add rust codes for space_complexity

codes/rust/Cargo.toml, codes/rust/chapter_array_and_linkedlist/linked_list.rs, codes/rust/chapter_computational_complexity/space_complexity.rs, codes/rust/chapter_stack_and_queue/linkedlist_deque.rs, codes/rust/chapter_stack_and_queue/linkedlist_queue.rs, codes/rust/chapter_stack_and_queue/linkedlist_stack.rs, codes/rust/include/include.rs, codes/zig/chapter_stack_and_queue/linkedlist_deque.zig, codes/zig/chapter_stack_and_queue/linkedlist_queue.zig, codes/zig/chapter_stack_and_queue/linkedlist_stack.zig
=> 🚀feat: add rust codes for linkedlist_stack, linkedlist_queue and linkedlist_deque

codes/go/chapter_stack_and_queue/array_deque.go, codes/go/chapter_stack_and_queue/deque_test.go
=> feat(go/deque): support go array deque

codes/c/chapter_stack_and_queue/CMakeLists.txt, codes/c/chapter_stack_and_queue/linkedlist_queue.c
=> feat(codes/c): Add linkedlist_queue.c

codes/c/chapter_stack_and_queue/CMakeLists.txt, codes/c/chapter_stack_and_queue/array_deque.c
=> feat(codes/c): Add array_deque.c

codes/rust/Cargo.toml, codes/rust/chapter_stack_and_queue/array_deque.rs, codes/zig/chapter_array_and_linkedlist/my_list.zig, codes/zig/chapter_heap/heap.zig, codes/zig/chapter_heap/my_heap.zig, codes/zig/chapter_stack_and_queue/array_queue.zig, codes/zig/chapter_stack_and_queue/deque.zig
=> 🚀feat: add rust codes for array_deque

docs/chapter_tree/binary_tree.md
=> fix(doc/go): fix binary_tree doc

codes/c/chapter_array_and_linkedlist/linked_list.c, docs/chapter_array_and_linkedlist/linked_list.md
=> update C linked_list init

codes/cpp/chapter_stack_and_queue/linkedlist_deque.cpp
=> Memory leak fix: the space was not freed when pop removed the element.

.gitignore, codes/c/chapter_sorting/CMakeLists.txt, codes/c/chapter_sorting/counting_sort.c, codes/go/chapter_sorting/count_sort_test.go, codes/go/chapter_sorting/counting_sort.go
=> feat(counting_sort): support counting_sort in c/go

codes/swift/Package.swift, codes/swift/chapter_sorting/counting_sort.swift
=> feat: add Swift codes for counting_sort article

codes/swift/chapter_computational_complexity/time_complexity.swift
=> refactor: use stride

codes/swift/Package.swift, codes/swift/chapter_sorting/bucket_sort.swift
=> feat: add Swift codes for bucket_sort article

codes/c/chapter_sorting/CMakeLists.txt, codes/c/chapter_sorting/bucket_sort.c, codes/c/include/print_util.h, codes/go/chapter_sorting/bucket_sort.go, codes/go/chapter_sorting/bucket_sort_test.go
=> feat(bucket_sort): add bucket_sort code in go/c

codes/dart/chapter_hashing/array_hash_map.dart, codes/dart/chapter_hashing/hash_map.dart, codes/dart/chapter_stack_and_queue/array_deque.dart, codes/dart/chapter_stack_and_queue/array_queue.dart, codes/dart/chapter_stack_and_queue/array_stack.dart, codes/dart/chapter_stack_and_queue/deque.dart, codes/dart/chapter_stack_and_queue/linkedlist_deque.dart, codes/dart/chapter_stack_and_queue/linkedlist_queue.dart, codes/dart/chapter_stack_and_queue/linkedlist_stack.dart, codes/dart/chapter_stack_and_queue/queue.dart, codes/dart/chapter_stack_and_queue/stack.dart
=> feat: add dart code for chapter_stack_and_queue and chapter_hashing

codes/dart/chapter_tree/avl_tree.dart, codes/dart/chapter_tree/binary_search_tree.dart, codes/dart/chapter_tree/binary_tree.dart, codes/dart/chapter_tree/binary_tree_bfs.dart, codes/dart/chapter_tree/binary_tree_dfs.dart, codes/dart/utils/tree_node.dart
=> feat: add dart code for chapter_tree

codes/javascript/chapter_sorting/bucket_sort.js, codes/javascript/chapter_sorting/counting_sort.js, codes/javascript/chapter_sorting/radix_sort.js, codes/typescript/chapter_sorting/bucket_sort.ts, codes/typescript/chapter_sorting/counting_sort.ts, codes/typescript/chapter_sorting/radix_sort.ts
=> Add JavaScript and TypeScript code of bucket sort, counting sort and radix sort (Chapter of Sorting)

codes/dart/chapter_heap/my_heap.dart, codes/dart/utils/print_util.dart
=> feat: add dart code for chapter_heap

codes/csharp/chapter_graph/graph_bfs.cs, codes/csharp/chapter_graph/graph_dfs.cs, codes/csharp/chapter_sorting/bucked_sort.cs, codes/csharp/chapter_sorting/counting_sort.cs, codes/csharp/chapter_sorting/radix_sort.cs
bucked_sort测试结果
counting_sort测试结果
radix_sort测试结果
=> feat(csharp/sorting): add bucked_sort, counting_sort, radix_sort

codes/csharp/chapter_backtracking/backtrack_find_constrained_paths.cs, codes/csharp/chapter_backtracking/preorder_find_constrained_paths.cs, codes/csharp/chapter_backtracking/preorder_find_nodes.cs, codes/csharp/chapter_backtracking/preorder_find_paths.cs
=> feat(csharp/backtracking): add csharp code in backtracking

codes/rust/Cargo.toml, codes/rust/chapter_tree/binary_tree_bfs.rs, codes/rust/chapter_tree/binary_tree_dfs.rs, codes/rust/include/tree_node.rs
=> ✨ feat(rust/tree): add binary_tree_bfs, binary_tree_dfs, 

codes/csharp/chapter_backtracking/backtrack_find_constrained_paths.cs, codes/csharp/chapter_backtracking/preorder_find_constrained_paths.cs, codes/csharp/chapter_backtracking/preorder_find_nodes.cs, codes/csharp/chapter_backtracking/preorder_find_paths.cs, codes/csharp/chapter_computational_complexity/space_complexity.cs, codes/csharp/chapter_graph/graph_adjacency_list.cs, codes/csharp/chapter_graph/graph_adjacency_matrix.cs, codes/csharp/chapter_graph/graph_bfs.cs, codes/csharp/chapter_graph/graph_dfs.cs, codes/csharp/chapter_hashing/array_hash_map.cs, codes/csharp/chapter_hashing/hash_map.cs, codes/csharp/chapter_heap/heap.cs, codes/csharp/chapter_heap/my_heap.cs, codes/csharp/chapter_stack_and_queue/array_stack.cs, codes/csharp/chapter_stack_and_queue/deque.cs, codes/csharp/chapter_stack_and_queue/linkedlist_queue.cs, codes/csharp/chapter_stack_and_queue/linkedlist_stack.cs, codes/csharp/chapter_stack_and_queue/queue.cs, codes/csharp/chapter_stack_and_queue/stack.cs, codes/csharp/chapter_tree/binary_tree_bfs.cs, codes/csharp/chapter_tree/binary_tree_dfs.cs, codes/csharp/include/PrintUtil.cs, codes/csharp/include/TreeNode.cs, codes/csharp/include/Vertex.cs
1. Change method signature from ArrToTree to ListToTree
2. Simplified code for print list
3. Use String alias
4. Change vertex val from property to field
5. Implement Print matrics with generic type
6. Method name in include use PascalCase
=> refactor: add/refactor method in include, simplified print code

codes/csharp/chapter_backtracking/permutations_i.cs, codes/csharp/chapter_backtracking/permutations_ii.cs, codes/csharp/chapter_backtracking/preorder_traversal_i_compact.cs
1.add permutations csharp code
2.remove unnecessary using
Test result:
=> feat(csharp/backtracking): add csharp code in permutations

codes/swift/Package.swift, codes/swift/chapter_backtracking/preorder_traversal_i_compact.swift, codes/swift/chapter_backtracking/preorder_traversal_ii_compact.swift, codes/swift/chapter_backtracking/preorder_traversal_iii_compact.swift, codes/swift/chapter_backtracking/preorder_traversal_iii_template.swift, codes/swift/chapter_tree/avl_tree.swift, codes/swift/chapter_tree/binary_search_tree.swift
=> feat: add Swift codes for backtracking_algorithm article

codes/swift/Package.swift, codes/swift/chapter_backtracking/permutations_i.swift, codes/swift/chapter_backtracking/permutations_ii.swift
=> feat: add Swift codes for permutations_problem article

codes/csharp/chapter_backtracking/n_queens.cs
=> feat(csharp/backtracking): add csharp code in n queens

codes/dart/chapter_tree/avl_tree.dart, codes/dart/chapter_tree/binary_search_tree.dart
=> Fix function call error and null safety

codes/swift/Package.swift, codes/swift/chapter_backtracking/n_queens.swift, codes/swift/chapter_backtracking/preorder_traversal_iii_template.swift
=> feat: add Swift codes for n_queens_problem article

codes/go/chapter_backtracking/n_queens.go, codes/go/chapter_backtracking/n_queens_test.go, codes/go/chapter_backtracking/permutation_test.go, codes/go/chapter_backtracking/permutations_i.go, codes/go/chapter_backtracking/permutations_ii.go, codes/go/chapter_backtracking/preorder_traversal_i_compact.go, codes/go/chapter_backtracking/preorder_traversal_ii_compact.go, codes/go/chapter_backtracking/preorder_traversal_iii_compact.go, codes/go/chapter_backtracking/preorder_traversal_iii_template.go, codes/go/chapter_backtracking/preorder_traversal_test.go
=> feat(go/backtracking): add go code

codes/go/chapter_sorting/counting_sort.go
=> fix:range issue

codes/dart/chapter_graph/graph_adjacency_list.dart, codes/dart/chapter_graph/graph_adjacency_matrix.dart, codes/dart/chapter_graph/graph_bfs.dart, codes/dart/chapter_graph/graph_dfs.dart, codes/dart/utils/print_util.dart, codes/dart/utils/vertex.dart
=> feat: add dart code for chapter_graph

codes/dart/chapter_searching/hashing_search.dart, codes/dart/chapter_searching/linear_search.dart, codes/dart/chapter_sorting/bucket_sort.dart, codes/dart/chapter_sorting/counting_sort.dart, codes/dart/utils/list_node.dart
counting_sort.dart
```
计数排序（无法排序对象）完成后 nums = [0, 0, 0, 1, 1, 2, 2, 2, 4, 4]
计数排序完成后 nums1 = [0, 0, 0, 1, 1, 2, 2, 2, 4, 4]
```
bucket_sort.dart
```
桶排序完成后 = [0.12, 0.17, 0.21, 0.23, 0.26, 0.39, 0.68, 0.72, 0.78, 0.94]
```
=> feat: add chapter_sorting and chapter_searching by dart

codes/swift/Package.swift, codes/swift/chapter_searching/binary_search_edge.swift
=> feat: add Swift codes for binary_search_edge article

codes/swift/Package.swift, codes/swift/chapter_sorting/selection_sort.swift
=> feat: add Swift codes for selection_sort article

codes/go/chapter_searching/binary_search_edge.go, codes/go/chapter_searching/binary_search_test.go, codes/go/chapter_sorting/heap_sort.go, codes/go/chapter_sorting/heap_sort_test.go, codes/go/chapter_sorting/selection_sort.go, codes/go/chapter_sorting/selection_sort_test.go
=> feat(sort/search): support heap/selection_sort/binary_search_edge in go code

codes/dart/chapter_array_and_linkedlist/array.dart, codes/dart/chapter_array_and_linkedlist/linked_list.dart, codes/dart/chapter_array_and_linkedlist/list.dart, codes/dart/chapter_array_and_linkedlist/my_list.dart, codes/dart/chapter_computational_complexity/space_complexity.dart, codes/dart/chapter_graph/graph_adjacency_matrix.dart, codes/dart/chapter_heap/my_heap.dart, codes/dart/chapter_sorting/bucket_sort.dart, codes/dart/chapter_stack_and_queue/array_deque.dart, codes/dart/chapter_stack_and_queue/array_queue.dart, codes/dart/chapter_stack_and_queue/deque.dart, codes/dart/chapter_stack_and_queue/queue.dart, codes/dart/chapter_stack_and_queue/stack.dart, codes/dart/utils/print_util.dart
=> Update Dart code to output same as Java

codes/csharp/chapter_searching/binary_search_edge.cs, codes/csharp/chapter_sorting/heap_sort.cs, codes/csharp/chapter_sorting/selection_sort.cs
binary search edge test result:
heap sort test result:
selection sort test result:
=> feat(csharp): add binary_search_edge, heap_sort, selection_sort

codes/dart/chapter_searching/binary_search_edge.dart, codes/dart/chapter_sorting/heap_sort.dart, codes/dart/chapter_sorting/selection_sort.dart
=> feat: complete dart code for chapter_searching and chapter_sorting

codes/csharp/chapter_heap/top_k.cs
=> feat(csharp): add top_k

codes/go/chapter_backtracking/subset_sum_i.go, codes/go/chapter_backtracking/subset_sum_i_naive.go, codes/go/chapter_backtracking/subset_sum_ii.go, codes/go/chapter_backtracking/subset_sum_test.go, codes/go/chapter_hashing/hash_map_chaining.go, codes/go/chapter_hashing/hash_map_open_addressing.go, codes/go/chapter_hashing/hash_map_test.go, codes/go/chapter_hashing/simple_hash.go, codes/go/chapter_heap/heap_test.go, codes/go/chapter_heap/top_k.go
=> feat(go): support new features with go code

codes/csharp/chapter_backtracking/subset_sum_i.cs, codes/csharp/chapter_backtracking/subset_sum_i_naive.cs, codes/csharp/chapter_backtracking/subset_sum_ii.cs
=> feat(csharp/backtracking): add subset_sum_i, _ii, _i_naive

codes/dart/chapter_hashing/built_in_hash.dart, codes/dart/chapter_hashing/hash_map_chaining.dart, codes/dart/chapter_hashing/hash_map_open_addressing.dart, codes/dart/chapter_hashing/simple_hash.dart, codes/java/chapter_hashing/hash_map_open_addressing.java, codes/java/chapter_hashing/simple_hash.java, docs/chapter_hashing/hash_algorithm.md
=> feat: complete Dart codes  for chapter_hashing

codes/csharp/chapter_hashing/built_in_hash.cs, codes/csharp/chapter_hashing/hash_map_chaining.cs, codes/csharp/chapter_hashing/hash_map_open_addressing.cs, codes/csharp/chapter_hashing/simple_hash.cs, docs/chapter_hashing/hash_algorithm.md
=> feat(csharp/hashing): add code and update docs to chapter hashing

codes/swift/chapter_sorting/bucket_sort.swift, codes/swift/chapter_tree/binary_search_tree.swift
=> fix: compiler error and reset root

codes/swift/Package.swift, codes/swift/chapter_hashing/array_hash_map.swift, codes/swift/chapter_hashing/hash_map_chaining.swift, codes/swift/chapter_hashing/hash_map_open_addressing.swift, codes/swift/utils/Pair.swift, docs/chapter_hashing/hash_map.md
=> feat: add Swift codes for hash_collision article

codes/swift/Package.swift, codes/swift/chapter_hashing/built_in_hash.swift, codes/swift/chapter_hashing/simple_hash.swift, codes/swift/utils/ListNode.swift
=> feat: add Swift codes for hash_algorithm article

codes/csharp/chapter_dynamic_programming/climbing_stairs_backtrack.cs, codes/csharp/chapter_dynamic_programming/climbing_stairs_constraint_dp.cs, codes/csharp/chapter_dynamic_programming/climbing_stairs_dfs.cs, codes/csharp/chapter_dynamic_programming/climbing_stairs_dfs_mem.cs, codes/csharp/chapter_dynamic_programming/climbing_stairs_dp.cs, codes/csharp/chapter_dynamic_programming/min_cost_climbing_stairs_dp.cs, codes/csharp/utils/PrintUtil.cs
=> feat(csharp): add csharp code for charper dynamic programming

codes/swift/Package.swift, codes/swift/chapter_heap/top_k.swift
=> feat: add Swift codes for top_k article

codes/swift/Package.swift, codes/swift/chapter_backtracking/subset_sum_i.swift, codes/swift/chapter_backtracking/subset_sum_i_naive.swift, codes/swift/chapter_backtracking/subset_sum_ii.swift
=> feat: add Swift codes for subset_sum_problem article

codes/csharp/chapter_dynamic_programming/knapsack.cs
=> feat(csharp): add csharp code for knapsack

codes/rust/chapter_sorting/heap_sort.rs
The console ouputs:
```
堆排序完成后 nums = [1, 1, 2, 3, 4, 5]
```
=> feat: add rust code for heap sort

codes/rust/Cargo.toml, codes/rust/chapter_dynamic_programming/climbing_stairs_backtrack.rs, codes/rust/chapter_dynamic_programming/climbing_stairs_constraint_dp.rs, codes/rust/chapter_dynamic_programming/climbing_stairs_dfs.rs, codes/rust/chapter_dynamic_programming/climbing_stairs_dfs_mem.rs, codes/rust/chapter_dynamic_programming/climbing_stairs_dp.rs, codes/rust/chapter_dynamic_programming/min_cost_climbing_stairs_dp.rs, codes/rust/chapter_searching/hashing_search.rs, codes/rust/chapter_searching/linear_search.rs, codes/rust/include/list_node.rs, codes/zig/.gitignore, codes/zig/build.zig, codes/zig/chapter_array_and_linkedlist/array.zig, codes/zig/chapter_computational_complexity/time_complexity.zig, codes/zig/chapter_computational_complexity/worst_best_time_complexity.zig, codes/zig/chapter_searching/binary_search.zig, codes/zig/chapter_searching/hashing_search.zig, codes/zig/chapter_searching/linear_search.zig, codes/zig/chapter_searching/two_sum.zig, codes/zig/chapter_sorting/radix_sort.zig, codes/zig/chapter_tree/avl_tree.zig
@krahets  Hi,
- commit 1 => zig : upgrade codes to version 0.11.0-dev.3944+2e424e019.
- commit 2 => rust : add codes for linear_search and hashing_search.
- commit 3 => rust : add codes for chapter_dynamic_programming.
=> zig : upgrade codes && rust : add codes for chapter_searching and chapter_dynamic_programming.

codes/csharp/chapter_dynamic_programming/knapsack.cs, codes/csharp/chapter_dynamic_programming/min_path_sum.cs
1. fix method name in knapsack
2. add csharp code for min path sum
test result:
=> fix(csharp): fix csharp method name in knapsack

codes/rust/Cargo.toml, codes/rust/chapter_backtracking/subset_sum_i.rs, codes/rust/chapter_backtracking/subset_sum_i_naive.rs, codes/rust/chapter_backtracking/subset_sum_ii.rs
@krahets  Hi,
- commit 1 => rust : add codes for chapter_backtracking.
=> rust : add codes for chapter_backtracking

codes/csharp/chapter_dynamic_programming/coin_change.cs, codes/csharp/chapter_dynamic_programming/coin_change_ii.cs, codes/csharp/chapter_dynamic_programming/unbounded_knapsack.cs
=> feat(csharp): add csharp code for unbounded knapsack

codes/csharp/chapter_dynamic_programming/edit_distance.cs
=> feat(csharp): add csharp code for edit distance

codes/rust/Cargo.toml, codes/rust/chapter_backtracking/n_queens.rs, codes/rust/chapter_backtracking/permutations_i.rs, codes/rust/chapter_backtracking/permutations_ii.rs, codes/rust/chapter_dynamic_programming/climbing_stairs_dfs.rs, codes/rust/chapter_dynamic_programming/climbing_stairs_dfs_mem.rs, codes/rust/chapter_dynamic_programming/climbing_stairs_dp.rs, codes/rust/chapter_dynamic_programming/coin_change.rs, codes/rust/chapter_dynamic_programming/coin_change_ii.rs, codes/rust/chapter_dynamic_programming/edit_distance.rs, codes/rust/chapter_dynamic_programming/knapsack.rs, codes/rust/chapter_dynamic_programming/min_cost_climbing_stairs_dp.rs, codes/rust/chapter_dynamic_programming/min_path_sum.rs, codes/rust/chapter_dynamic_programming/unbounded_knapsack.rs, codes/zig/build.zig, codes/zig/chapter_dynamic_programming/climbing_stairs_backtrack.zig, codes/zig/chapter_dynamic_programming/climbing_stairs_constraint_dp.zig, codes/zig/chapter_dynamic_programming/climbing_stairs_dfs.zig, codes/zig/chapter_dynamic_programming/climbing_stairs_dfs_mem.zig, codes/zig/chapter_dynamic_programming/climbing_stairs_dp.zig, codes/zig/chapter_dynamic_programming/coin_change.zig, codes/zig/chapter_dynamic_programming/coin_change_ii.zig, codes/zig/chapter_dynamic_programming/edit_distance.zig, codes/zig/chapter_dynamic_programming/knapsack.zig, codes/zig/chapter_dynamic_programming/min_cost_climbing_stairs_dp.zig, codes/zig/chapter_dynamic_programming/min_path_sum.zig, codes/zig/chapter_dynamic_programming/unbounded_knapsack.zig
@krahets  Hi,
- commit 1 => rust : add codes for chapter_dynamic_programming.
- commit 2 => zig : add codes for chapter_dynamic_programming.
- commit 3 => rust : add codes for chapter_backtracking.
=> rust and zig : add codes for chapter_dynamic_programming

codes/rust/Cargo.toml, codes/rust/chapter_backtracking/preorder_traversal_i_compact.rs, codes/rust/chapter_backtracking/preorder_traversal_ii_compact.rs, codes/rust/chapter_backtracking/preorder_traversal_iii_compact.rs, codes/rust/chapter_backtracking/preorder_traversal_iii_template.rs, codes/zig/chapter_dynamic_programming/climbing_stairs_backtrack.zig, codes/zig/chapter_dynamic_programming/climbing_stairs_constraint_dp.zig, codes/zig/chapter_dynamic_programming/climbing_stairs_dfs.zig, codes/zig/chapter_dynamic_programming/climbing_stairs_dfs_mem.zig, codes/zig/chapter_dynamic_programming/climbing_stairs_dp.zig, codes/zig/chapter_dynamic_programming/coin_change.zig, codes/zig/chapter_dynamic_programming/coin_change_ii.zig, codes/zig/chapter_dynamic_programming/edit_distance.zig, codes/zig/chapter_dynamic_programming/knapsack.zig, codes/zig/chapter_dynamic_programming/min_cost_climbing_stairs_dp.zig, codes/zig/chapter_dynamic_programming/min_path_sum.zig, codes/zig/chapter_dynamic_programming/unbounded_knapsack.zig
@krahets  Hi. All the codes outpus are the same with Java codes.
- commit 1 => zig : update codes style for chapter_dynamic_programming.
- commit 2 => rust : add codes for chapter_backtracking.
=> zig : update codes style && rust : add codes for chapter_backtracking.

codes/csharp/chapter_divide_and_conquer/binary_search_recur.cs, codes/csharp/chapter_divide_and_conquer/build_tree.cs, codes/csharp/chapter_divide_and_conquer/hanota.cs, docs/chapter_divide_and_conquer/hanota_problem.md
=> feat(csharp): add csharp code for charper divide and conquer

codes/csharp/chapter_greedy/coin_change_greedy.cs, codes/csharp/chapter_greedy/fractional_knapsack.cs, codes/csharp/chapter_greedy/max_capacity.cs, codes/csharp/chapter_greedy/max_product_cutting.cs
=> feat(csharp): add csharp code for charper greedy

codes/rust/Cargo.toml, codes/rust/chapter_greedy/coin_change_greedy.rs, codes/rust/chapter_greedy/fractional_knapsack.rs, codes/rust/chapter_greedy/max_capacity.rs, codes/rust/chapter_greedy/max_product_cutting.rs
Outputs of `coin_change_greedy.rs`:
```
coins = [1, 5, 10, 20, 50, 100], amt = 186
凑到 186 所需的最少硬币数量为 6
coins = [1, 20, 50], amt = 60
凑到 60 所需的最少硬币数量为 11
实际上需要的最少数量为 3 ，即 20 + 20 + 20
coins = [1, 49, 50], amt = 98
凑到 98 所需的最少硬币数量为 49
实际上需要的最少数量为 2 ，即 49 + 49
```
Outputs of `fractional_knapsack.rs`:
```
不超过背包容量的最大物品价值为 277.5
```
Outputs of `max_capacity.rs`:
```
最大容量为 28
```
Outputs of `max_product_cutting.rs`:
```
最大切分乘积为1549681956
```
=> feat: add rust codes for chapter greedy

codes/java/chapter_greedy/max_product_cutting.java
=> fix: add space in print

codes/go/chapter_greedy/coin_change_greedy.go, codes/go/chapter_greedy/coin_change_greedy_test.go, codes/go/chapter_greedy/fractional_knapsack.go, codes/go/chapter_greedy/fractional_knapsack_test.go, codes/go/chapter_greedy/max_capacity.go, codes/go/chapter_greedy/max_capacity_test.go, codes/go/chapter_greedy/max_product_cutting.go, codes/go/chapter_greedy/max_product_cutting_test.go
=> feat(go/greedy): add greedy in go code

codes/go/chapter_dynamic_programming/climbing_stairs_backtrack.go, codes/go/chapter_dynamic_programming/climbing_stairs_constraint_dp.go, codes/go/chapter_dynamic_programming/climbing_stairs_dfs.go, codes/go/chapter_dynamic_programming/climbing_stairs_dfs_mem.go, codes/go/chapter_dynamic_programming/climbing_stairs_dp.go, codes/go/chapter_dynamic_programming/climbing_stairs_test.go, codes/go/chapter_dynamic_programming/coin_change.go, codes/go/chapter_dynamic_programming/coin_change_ii.go, codes/go/chapter_dynamic_programming/coin_change_test.go, codes/go/chapter_dynamic_programming/edit_distance.go, codes/go/chapter_dynamic_programming/edit_distance_test.go, codes/go/chapter_dynamic_programming/knapsack.go, codes/go/chapter_dynamic_programming/knapsack_test.go, codes/go/chapter_dynamic_programming/min_cost_climbing_stairs_dp.go, codes/go/chapter_dynamic_programming/min_path_sum.go, codes/go/chapter_dynamic_programming/min_path_sum_test.go, codes/go/chapter_dynamic_programming/unbounded_knapsack.go
=> feat(go/dp): support dynamic programming

codes/csharp/chapter_array_and_linkedlist/list.cs, codes/csharp/chapter_array_and_linkedlist/my_list.cs, codes/csharp/chapter_computational_complexity/time_complexity.cs, codes/csharp/chapter_searching/two_sum.cs, codes/csharp/chapter_stack_and_queue/queue.cs, codes/csharp/chapter_stack_and_queue/stack.cs, docs/chapter_array_and_linkedlist/linked_list.md, docs/chapter_array_and_linkedlist/list.md, docs/chapter_computational_complexity/space_complexity.md, docs/chapter_computational_complexity/time_complexity.md, docs/chapter_hashing/hash_map.md, docs/chapter_stack_and_queue/queue.md, docs/chapter_stack_and_queue/stack.md
=> fix(csharp): reformat csharp codes and docs

codes/rust/chapter_array_and_linkedlist/array.rs, codes/rust/chapter_array_and_linkedlist/list.rs, codes/rust/chapter_array_and_linkedlist/my_list.rs, codes/rust/chapter_backtracking/subset_sum_i.rs, codes/rust/chapter_backtracking/subset_sum_i_naive.rs, codes/rust/chapter_backtracking/subset_sum_ii.rs, codes/rust/chapter_divide_and_conquer/hanota.rs, codes/rust/chapter_hashing/array_hash_map.rs, codes/rust/chapter_searching/hashing_search.rs, codes/rust/chapter_searching/linear_search.rs, codes/rust/chapter_sorting/quick_sort.rs, codes/rust/chapter_stack_and_queue/array_queue.rs, codes/rust/chapter_stack_and_queue/deque.rs, codes/rust/chapter_stack_and_queue/linkedlist_deque.rs, codes/rust/chapter_tree/binary_search_tree.rs, codes/rust/chapter_tree/binary_tree.rs, codes/rust/chapter_tree/binary_tree_bfs.rs, codes/rust/chapter_tree/binary_tree_dfs.rs
=> fix: check the rust codes and fix them

codes/rust/Cargo.toml, codes/rust/chapter_tree/array_binary_tree.rs, codes/rust/include/tree_node.rs
The outputs:
```
初始化二叉树
二叉树的数组表示：
[1, 2, 3, 4, null, 6, 7, 8, 9, null, null, 12, null, null, 15]
二叉树的链表表示：
/——— 15
/——— 7
/——— 3
|    \——— 6
|        \——— 12
——— 1
\——— 2
|    /——— 9
\——— 4
\——— 8
当前节点的索引为 1 ，值为 2
其左子节点的索引为 3 ，值为 4
其右子节点的索引为 4 ，值为 null
其父节点的索引为 0 ，值为 1
层序遍历为：[1, 2, 3, 4, 6, 7, 8, 9, 12, 15]
前序遍历为：[1, 2, 4, 8, 9, 3, 6, 12, 7, 15]
中序遍历为：[8, 4, 9, 2, 1, 12, 6, 3, 7, 15]
后序遍历为：[8, 9, 4, 2, 12, 6, 15, 7, 3, 1]
```
=> feat: add rust codes for array binary tree

codes/go/chapter_backtracking/preorder_traversal_i_compact.go, codes/go/chapter_backtracking/preorder_traversal_ii_compact.go, codes/go/chapter_backtracking/preorder_traversal_iii_compact.go, codes/go/chapter_backtracking/preorder_traversal_test.go, codes/go/chapter_tree/array_binary_tree.go, codes/go/chapter_tree/array_binary_tree_test.go, codes/go/chapter_tree/avl_tree.go, codes/go/chapter_tree/binary_search_tree.go, codes/go/chapter_tree/binary_tree_bfs.go, codes/go/chapter_tree/binary_tree_bfs_test.go, codes/go/chapter_tree/binary_tree_dfs.go, codes/go/chapter_tree/binary_tree_dfs_test.go, codes/go/pkg/print_utils.go, codes/go/pkg/tree_node.go, codes/go/pkg/tree_node_test.go
=> feat(go/tree): support array binary tree

codes/rust/Cargo.toml, codes/rust/chapter_hashing/build_in_hash.rs, codes/rust/chapter_hashing/hash_map_chaining.rs, codes/rust/chapter_hashing/hash_map_open_addressing.rs
Accidentally closed pull request #582 ,sorry.
=> feat: add rust code for build_in_hash and hash_collision

codes/javascript/chapter_dynamic_programming/climbing_stairs_backtrack.js, codes/javascript/chapter_dynamic_programming/climbing_stairs_dfs.js, codes/javascript/chapter_dynamic_programming/climbing_stairs_dfs_mem.js, codes/javascript/chapter_dynamic_programming/climbing_stairs_dp.js, codes/typescript/chapter_dynamic_programming/climbing_stairs_backtrack.ts, codes/typescript/chapter_dynamic_programming/climbing_stairs_dfs.ts, codes/typescript/chapter_dynamic_programming/climbing_stairs_dfs_mem.ts, codes/typescript/chapter_dynamic_programming/climbing_stairs_dp.ts
=> feat(chapter_dynamic_programming): Add js and ts codes for chapter 14.1

codes/cpp/chapter_hashing/hash_map_chaining.cpp
=> fix: Object pointer not deleted

codes/swift/chapter_stack_and_queue/linkedlist_deque.swift
=> fix: break reference cycling

codes/csharp/chapter_searching/binary_search_edge.cs, codes/csharp/chapter_searching/binary_search_insertion.cs
=> feat(csharp): add binary search csharp codes

codes/dart/chapter_dynamic_programming/climbing_stairs_backtrack.dart, codes/dart/chapter_dynamic_programming/climbing_stairs_constraint_dp.dart, codes/dart/chapter_dynamic_programming/climbing_stairs_dfs.dart, codes/dart/chapter_dynamic_programming/climbing_stairs_dfs_mem.dart, codes/dart/chapter_dynamic_programming/climbing_stairs_dp.dart, codes/dart/chapter_dynamic_programming/coin_change.dart, codes/dart/chapter_dynamic_programming/coin_change_ii.dart, codes/dart/chapter_dynamic_programming/edit_distance.dart, codes/dart/chapter_dynamic_programming/knapsack.dart, codes/dart/chapter_dynamic_programming/min_cost_climbing_stairs_dp.dart, codes/dart/chapter_dynamic_programming/min_path_sum.dart, codes/dart/chapter_dynamic_programming/unbounded_knapsack.dart, codes/dart/chapter_greedy/coin_change_greedy.dart, codes/dart/chapter_greedy/fractional_knapsack.dart, codes/dart/chapter_greedy/max_capacity.dart, codes/dart/chapter_greedy/max_product_cutting.dart
=> feat: Add Dart codes for chapter_dynamic_programming and chapter_greedy

codes/rust/chapter_searching/binary_search.rs
See 👉 https://github.com/krahets/hello-algo/discussions/52?sort=new#discussioncomment-6708590
=> Fix the bug of index in rust codes

docs/chapter_appendix/installation.md
=> fix(docs): add official configuration tutorial for csharp

codes/go/chapter_dynamic_programming/coin_change_ii.go, codes/go/chapter_searching/binary_search_edge.go, codes/go/chapter_searching/binary_search_insertion.go, codes/go/chapter_searching/binary_search_test.go
=> feat(go): support binary search & fix comments

codes/c/chapter_heap/my_heap.c, codes/go/chapter_computational_complexity/iteration.go, codes/go/chapter_computational_complexity/iteration_test.go, codes/go/chapter_computational_complexity/recursion.go, codes/go/chapter_computational_complexity/recursion_test.go, codes/go/chapter_heap/my_heap.go
=> feat(go): add iterration/recursion & fix bugs

codes/csharp/GlobalUsing.cs, codes/csharp/chapter_computational_complexity/iteration.cs, codes/csharp/chapter_computational_complexity/recursion.cs
=> feat(csharp): add the section of iteration and recursion

docs/chapter_searching/binary_search.md
=> fix: binary_search.md

codes/rust/chapter_dynamic_programming/coin_change_ii.rs
=> Fix the bug of wrong function call

codes/dart/chapter_tree/binary_search_tree.dart
=> fix dart code for binary_search_tree

codes/csharp/chapter_tree/binary_search_tree.cs
=> feat(csharp): fix binary_search_tree code

codes/rust/Cargo.toml, codes/rust/chapter_computational_complexity/iteration.rs, codes/rust/chapter_computational_complexity/recursion.rs, codes/rust/chapter_tree/binary_search_tree.rs
The outputs of `iteration.rs`:
```
for 循环的求和结果 res = 15
while 循环的求和结果 res = 15
while 循环（两次更新）求和结果 res = 5
双层 for 循环的遍历结果 (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5),
```
The outputs of `recursion.rs`:
```
递归函数的求和结果 res = 15
尾递归函数的求和结果 res = 15
斐波那契数列的第 5 项为 3
```
=> feat: add rust codes for chapter computational complexity

codes/javascript/chapter_computational_complexity/iteration.js, codes/javascript/chapter_computational_complexity/recursion.js, codes/typescript/chapter_computational_complexity/iteration.ts, codes/typescript/chapter_computational_complexity/recursion.ts
=> Iteration and recursion code in js/ts

codes/swift/Package.swift, codes/swift/chapter_computational_complexity/iteration.swift, codes/swift/chapter_computational_complexity/recursion.swift
=> feat: add Swift codes for iteration_and_recursion article

codes/swift/chapter_tree/binary_search_tree.swift
=> refactor: remove buildTree

codes/javascript/chapter_tree/binary_search_tree.js, codes/typescript/chapter_tree/avl_tree.ts, codes/typescript/chapter_tree/binary_search_tree.ts
=> Fix binary_search_tree TS code and update JS code style

codes/rust/Cargo.toml, codes/rust/chapter_hashing/simple_hash.rs
The output of `simple_hash.rs`:
```
加法哈希值为 60032
乘法哈希值为 742108061
异或哈希值为 512
旋转哈希值为 999652792
```
=> feat: add rust codes for simple_hash

docs/stylesheets/extra.css
=> style: Make the picture not glare in dark theme

codes/javascript/chapter_stack_and_queue/array_queue.js, codes/javascript/chapter_stack_and_queue/array_stack.js, codes/typescript/chapter_stack_and_queue/array_queue.ts, codes/typescript/chapter_stack_and_queue/array_stack.ts
=> fix: modify a function name in array_stack.js(ts) and array_queue.js(ts)

codes/csharp/chapter_computational_complexity/iteration.cs
=> fix:: Sync the while loop in iteration.cs with other languages

docs/chapter_stack_and_queue/stack.md
=> feat: add Rust code in stack.md

docs/chapter_stack_and_queue/deque.md, docs/chapter_stack_and_queue/queue.md
=> feat: add Rust code in queue.md and deque.md

docs/chapter_array_and_linkedlist/linked_list.md, docs/chapter_computational_complexity/space_complexity.md, docs/chapter_tree/avl_tree.md, docs/chapter_tree/binary_tree.md
Per https://github.com/krahets/hello-algo/pull/439, following PEP585 typing.
=> follow PEP585 typing

codes/java/chapter_hashing/hash_map_open_addressing.java
1. put keyA, hashFunc 在位置 5 
2. put key B, hashFunc 在位置  5. 和 A冲突，插入位置6
3. remove keyA,位置5removed
4. put keyB, hashFunc 在位置  5. 没有冲突，插入位置5
5. remove keyB, 位置5removed
6. get keyB, 此时会出bug，会访问到位置6. 实际上keyB 已经删除了
=> fix: Update hash_map_open_addressing.java

codes/javascript/chapter_backtracking/subset_sum_i.js, codes/javascript/chapter_backtracking/subset_sum_ii.js, codes/typescript/chapter_backtracking/subset_sum_i.ts, codes/typescript/chapter_backtracking/subset_sum_ii.ts
=> Fix JS and TS sort bugs for subset_sum

codes/csharp/chapter_computational_complexity/recursion.cs, codes/csharp/chapter_hashing/hash_map_open_addressing.cs
=> feat(csharp): add forLoopRecur and new HashMapOpenAddressing

codes/swift/chapter_computational_complexity/recursion.swift, codes/swift/chapter_dynamic_programming/min_cost_climbing_stairs_dp.swift, codes/swift/chapter_hashing/hash_map_open_addressing.swift
=> feat(Swift): update min_cost_climbing_stairs_dp and hash_map_open_addressing

codes/dart/chapter_computational_complexity/recursion.dart, codes/dart/chapter_hashing/hash_map_chaining.dart, codes/dart/chapter_hashing/hash_map_open_addressing.dart
=> feat(dart): add forLoopRecur and update HashMapOpenAddressing

docs/chapter_graph/graph_traversal.md
=> fix a typo in graph_traversal.md

codes/cpp/chapter_hashing/hash_map.cpp, docs/chapter_hashing/hash_map.md
=> fix(cpp). update hash_map

codes/rust/chapter_computational_complexity/recursion.rs
=> feat: add for-loop-recur rust codes

codes/rust/chapter_divide_and_conquer/build_tree.rs
=> fix: the rust variable should have a snake case name

docs/chapter_backtracking/backtracking_algorithm.md, docs/chapter_data_structure/basic_data_types.md, docs/chapter_hashing/hash_algorithm.md, docs/chapter_heap/heap.md, docs/chapter_stack_and_queue/stack.md, docs/chapter_tree/array_representation_of_tree.md, docs/chapter_tree/avl_tree.md, docs/chapter_tree/binary_tree.md
=> feat: add rust docs

codes/c/chapter_hashing/hash_map_chaining.c
=> fix get() in hash_map_chaining.c

codes/c/chapter_hashing/hash_map_chaining.c, docs/chapter_hashing/hash_collision.md
=> refactor: Improve the hash_map_chaining.c implementation.

codes/c/chapter_computational_complexity/recursion.c
=> feat: add forLoopRecur in recursion.c

codes/c/chapter_divide_and_conquer/CMakeLists.txt, codes/c/chapter_divide_and_conquer/build_tree.c
前序遍历 = [3, 9, 2, 1, 7]
中序遍历 = [9, 3, 1, 2, 7]
构建的二叉树为：
/———7
/———2
|    \———1
———3
\———9
=> feat: build_tree.c translation

codes/c/chapter_backtracking/CMakeLists.txt, codes/c/chapter_backtracking/permutations_ii.c
=> feat: add permutations_ii.c and re-implement permutations_i.c

codes/zig/build.zig
=> upate build.zig

.github/workflows/swift.yml
=> Add CI check for Swift

docs/chapter_array_and_linkedlist/linked_list.md
Communicated with Krahets and Justin and let's do the modifications files by files.
=> fix: Removed unnecessary JS & TS codes in linked_list.md

.github/workflows/dotnet.yml, codes/csharp/csharp.sln
=> feat(csharp): add .net building and testing workflow, solution file

.github/workflows/dotnet.yml, .github/workflows/python.yml, .github/workflows/swift.yml
=> Add workflow_dispatch to Swift, Python and C# CI Check

.github/workflows/dart.yml, codes/dart/build.dart, codes/dart/chapter_array_and_linkedlist/array.dart, codes/dart/chapter_array_and_linkedlist/list.dart, codes/dart/chapter_computational_complexity/space_complexity.dart, codes/dart/chapter_computational_complexity/time_complexity.dart
=> feat(dart): Add build check for Dart

.github/workflows/dart.yml
=> CI(dart): Cancel beta and dev Dart SDK

codes/rust/chapter_sorting/merge_sort.rs
=> refactor: re-implement the rust codes of  merge sort

codes/dart/chapter_sorting/merge_sort.dart
=> refactor(dart): Re-implement merge sort function

codes/typescript/chapter_heap/my_heap.ts, codes/typescript/chapter_heap/top_k.ts
=> feat: refactor top_k.ts

codes/c/chapter_graph/graph_adjacency_list.c, codes/c/chapter_graph/graph_adjacency_list_test.c, codes/c/chapter_graph/graph_adjacency_matrix.c, codes/c/chapter_graph/graph_bfs.c, codes/c/chapter_graph/graph_dfs.c, codes/c/utils/common.h, codes/c/utils/vertex.h
=> feat: Reimplement the graph code for C

docs/chapter_appendix/terminology.md
Added two missing terminologies that are present in the book:
* AVL tree
* Red Black tree
=> Add missing terminologies

Dockerfile, codes/Dockerfile, codes/docker-compose.yml, docker-compose.yml
=> feat: Add Docker for code debugging

codes/.env, codes/Dockerfile, codes/docker-compose.yml
=> feat: add csharp sdk to dockerfile

codes/rust/chapter_array_and_linkedlist/my_list.rs
See here: https://github.com/krahets/hello-algo/discussions/32#discussioncomment-7378599
=> Unsize type must be greater than or equal to 0

docs/chapter_array_and_linkedlist/linked_list.md
There is no need to declare next
=> fix: Update linked_list.md

codes/javascript/chapter_tree/array_binary_tree.js, codes/typescript/chapter_tree/array_binary_tree.ts
=> fix: the bug for the array binary tree from ts and js code

docs-en/chapter_computational_complexity/index.md
=> translate: Embellish chapter_computational_complexity/index.md

codes/rust/chapter_stack_and_queue/stack.rs, docs/chapter_stack_and_queue/stack.md
See here 👉 https://github.com/krahets/hello-algo/discussions/64#discussioncomment-7509480
=> Use Vec.last() method to access the top item of stack.

.github/workflows/c.yml, .github/workflows/cpp.yml
=> feat: Add auto-build-and-test workflow for C and C++

docs/chapter_data_structure/basic_data_types.md
See here 👉 https://github.com/krahets/hello-algo/discussions/46#discussioncomment-7538370
=> Fix the type annotation in Rust

.github/workflows/rust.yml
=> feat: add rust workflow

docs/chapter_array_and_linkedlist/list.md
=> fix: Initialize go empty slice

codes/c/chapter_hashing/hash_map_chaining.c, codes/c/chapter_sorting/counting_sort.c, codes/c/chapter_sorting/quick_sort.c, codes/go/chapter_hashing/hash_map_open_addressing.go
=> fix: Several code bug fixes

docs-en/chapter_computational_complexity/summary.md
This PR is translate chapter_computational_complexity/summary.md to english, [project link](https://github.com/users/krahets/projects/2/views/4?pane=issue&itemId=43506350).
=> translation: chapter_computational_complexity/summary to en

docs/chapter_appendix/installation.md, docs/chapter_appendix/terminology.md, docs/index.md
=> Several bug fixes and improvements

codes/go/chapter_backtracking/preorder_traversal_ii_compact.go, codes/go/chapter_hashing/hash_map_chaining.go, codes/go/chapter_hashing/hash_map_open_addressing.go
=> fix(go): fix go code , refer to @joengtou @wcig @shenjq

README.md
=> translation: Update README.md

docs-en/chapter_introduction/index.md
sorry, first time doing this... now this is the final change. changes:
title of the chapter is shorter.
refined the abstract.
=> translation: Update chapter_introduction/index.md

codes/rust/chapter_tree/binary_search_tree.rs
See here 👉 https://github.com/krahets/hello-algo/discussions/27#discussioncomment-7919887
=> Fix the issue of discuss comment 7919887

docs-en/chapter_introduction/algorithms_are_everywhere.md
I made changes to yuelinxin's suggestions.
again thank you so much for your suggestion yuelinxin!
=> translation: Update algorithms_are_everywhere.md

docs-en/chapter_data_structure/index.md
changed a bit of the abstract part.
=> translation: Update chapter_data_structure/index.md

codes/rust/chapter_searching/binary_search.rs
See here 👉 https://github.com/krahets/hello-algo/discussions/52#discussioncomment-7938404
=> Fix the issue of the comment 7938404

docs-en/chapter_array_and_linkedlist/array.md, docs/chapter_array_and_linkedlist/array.md
=> fix(csharp): unified array statement

codes/c/chapter_hashing/hash_map_open_addressing.c, codes/c/chapter_sorting/counting_sort.c, codes/c/chapter_tree/binary_search_tree.c
=> Fix some code bugs

codes/cpp/chapter_array_and_linkedlist/CMakeLists.txt
=> fix(cpp): cmake compile `my_list.cpp` for target list

codes/javascript/chapter_computational_complexity/recursion.js, codes/typescript/chapter_computational_complexity/recursion.ts
=> Fix: recursion bug for JS and TS

codes/csharp/chapter_computational_complexity/iteration.cs
=> fix(csharp): while loop II comment

codes/c/chapter_stack_and_queue/linkedlist_queue.c
=> fix(linkedlist_queue.c): Remove redundant conditional judgments.

docs-en/chapter_array_and_linkedlist/linked_list.md, docs-en/chapter_array_and_linkedlist/list.md
=> translation: Update chapter_array_and_linkedlist/list.md

codes/rust/chapter_sorting/selection_sort.rs
See here 👉 <https://github.com/krahets/hello-algo/discussions/514>
=> Fix the Rust code bug mentioned in discussion 514

docs-en/chapter_stack_and_queue/stack.md
=> translation:Update chapter_stack_and_queue/stack.md

codes/go/chapter_backtracking/preorder_traversal_iii_compact.go, codes/go/chapter_backtracking/preorder_traversal_iii_template.go
- [] This PR represents the translation of a single, complete document, or contains only bug fixes.
- [] The translation accurately conveys the original meaning and intent of the Chinese version. If deviations exist, I have provided explanatory comments to clarify the reasons.
=> fix(go): record slice array result, fixed #1075

codes/c/chapter_tree/binary_search_tree.c, codes/c/utils/common_test.c
=> fix some bugs in c codes

codes/kotlin/chapter_dynamic_programming/climbing_stairs_backtrack.kt, codes/kotlin/chapter_dynamic_programming/climbing_stairs_constraint_dp.kt, codes/kotlin/chapter_dynamic_programming/climbing_stairs_dfs.kt, codes/kotlin/chapter_dynamic_programming/climbing_stairs_dp.kt, codes/kotlin/chapter_dynamic_programming/climbing_stiars_dfs_mem.kt, codes/kotlin/chapter_dynamic_programming/coin_change.kt, codes/kotlin/chapter_dynamic_programming/coin_change_ii.kt, codes/kotlin/chapter_dynamic_programming/edit_distance.kt, codes/kotlin/chapter_dynamic_programming/knapsack.kt, codes/kotlin/chapter_dynamic_programming/min_cost_climbing_stairs_dp.kt, codes/kotlin/chapter_dynamic_programming/min_path_sum.kt, codes/kotlin/chapter_dynamic_programming/unbounded_knapsack.kt
=> Add kotlin code for dynamic programming

docs-en/chapter_stack_and_queue/deque.md
=> translation: Update chapter_stack_and_queue/deque.md

codes/kotlin/chapter_searching/binary_search.kt, codes/kotlin/chapter_searching/binary_search_edge.kt, codes/kotlin/chapter_searching/binary_search_insertion.kt, codes/kotlin/chapter_searching/hashing_search.kt, codes/kotlin/chapter_searching/linear_search.kt, codes/kotlin/chapter_searching/two_sum.kt
=> Add kotlin code for the chapter of searching

codes/rust/chapter_array_and_linkedlist/array.rs, codes/rust/chapter_array_and_linkedlist/linked_list.rs, codes/rust/chapter_sorting/quick_sort.rs, codes/rust/include/list_node.rs
fix rust compile warning and array print error and some linked list error, jus reading the rust code, will try my best to make rust code more readable and more elegantly.
=> Fix rust compile warning and an obvious print error in array.rs

docs-en/chapter_stack_and_queue/queue.md, docs/chapter_appendix/terminology.md
This commit mainly standardizes the terminology representing queue.
=> translation: Update chapter_stack_and_queue/queue.md

docs-en/chapter_computational_complexity/iteration_and_recursion.md
=> translation: Update chapter_computational_complexity/iteration_and_recursion.md

codes/kotlin/chapter_array_and_linkedlist/array.kt, codes/kotlin/chapter_stack_and_queue/array_deque.kt, codes/kotlin/chapter_stack_and_queue/array_queue.kt, codes/kotlin/chapter_stack_and_queue/array_stack.kt, codes/kotlin/chapter_stack_and_queue/deque.kt, codes/kotlin/chapter_stack_and_queue/linkedlist_deque.kt, codes/kotlin/chapter_stack_and_queue/linkedlist_queue.kt, codes/kotlin/chapter_stack_and_queue/linkedlist_stack.kt, codes/kotlin/chapter_stack_and_queue/queue.kt, codes/kotlin/chapter_stack_and_queue/stack.kt
=> Add kotlin code for the chapter of stack and queue

docs-en/chapter_computational_complexity/space_complexity.md, docs/chapter_computational_complexity/space_complexity.md
=> Add return value for recur function of Python in space complexity

codes/kotlin/utils/ListNode.kt, codes/kotlin/utils/PrintUtil.kt, codes/kotlin/utils/TreeNode.kt, codes/kotlin/utils/Vertex.kt
=> Add kotlin code for the utils file

docs/chapter_array_and_linkedlist/linked_list.md, docs/chapter_array_and_linkedlist/list.md
=> Add kotlin code block for chapter array and linkedlist

docs/chapter_array_and_linkedlist/array.md, docs/chapter_backtracking/backtracking_algorithm.md
=> Add kotlin code block for array.md and backtracking_algorithm.md

docs/chapter_hashing/hash_algorithm.md, docs/chapter_hashing/hash_map.md
=> Add kotlin code block for chapter_hashing

codes/ruby/utils/list_node.rb, docs/chapter_array_and_linkedlist/linked_list.md, docs/chapter_array_and_linkedlist/list.md
Fix some inconsistent comments.
---
=> Fix inconsistent comments Ruby - chapter array and linked list

codes/ruby/chapter_array_and_linkedlist/array.rb, codes/ruby/chapter_array_and_linkedlist/linked_list.rb, codes/ruby/chapter_array_and_linkedlist/list.rb, codes/ruby/chapter_array_and_linkedlist/my_list.rb, codes/ruby/chapter_computational_complexity/iteration.rb, codes/ruby/chapter_computational_complexity/recursion.rb, codes/ruby/chapter_computational_complexity/space_complexity.rb, codes/ruby/chapter_computational_complexity/time_complexity.rb, codes/ruby/chapter_computational_complexity/worst_best_time_complexity.rb, codes/ruby/utils/list_node.rb, codes/ruby/utils/print_util.rb, docs/chapter_array_and_linkedlist/linked_list.md, docs/chapter_array_and_linkedlist/list.md, docs/chapter_computational_complexity/space_complexity.md
=> Fix adapt missing ruby style guide

docs/chapter_data_structure/basic_data_types.md
There is a small code block for Ruby in chapter "Data Structure". So I create this PR to fulfill it.
---
=> feat: Add Ruby code block - chapter "Data Structure"

en/docs/chapter_hashing/summary.md
=> translation: chapter_hashing/summary.md 

zh-hant/README.md
=> fix: zh-hant/README.md `關聯 -> 聯繫`

.github/workflows/ruby.yml, codes/ruby/test_all.rb
=> Add Ruby test CI

codes/java/chapter_sorting/radix_sort.java
=> fix(Java): Add the brackets to `for` loop

codes/ruby/chapter_array_and_linkedlist/array.rb, codes/ruby/chapter_array_and_linkedlist/linked_list.rb, codes/ruby/chapter_array_and_linkedlist/list.rb, codes/ruby/chapter_array_and_linkedlist/my_list.rb, codes/ruby/chapter_computational_complexity/iteration.rb, codes/ruby/chapter_computational_complexity/recursion.rb, codes/ruby/chapter_computational_complexity/space_complexity.rb, codes/ruby/chapter_computational_complexity/time_complexity.rb, codes/ruby/chapter_computational_complexity/worst_best_time_complexity.rb, codes/ruby/chapter_stack_and_queue/array_deque.rb, codes/ruby/chapter_stack_and_queue/array_queue.rb, codes/ruby/chapter_stack_and_queue/array_stack.rb, codes/ruby/chapter_stack_and_queue/deque.rb, codes/ruby/chapter_stack_and_queue/linkedlist_deque.rb, codes/ruby/chapter_stack_and_queue/linkedlist_queue.rb, codes/ruby/chapter_stack_and_queue/linkedlist_stack.rb, codes/ruby/chapter_stack_and_queue/queue.rb, codes/ruby/chapter_stack_and_queue/stack.rb
In #1262, we have the `binary_search_edge` file that import a method of `binary_search_insertion` file. To prevent the driver code in the `binary_search_insertion` file being triggered when running the `binary_search_edge` file, we should put the driver code into this block:
```rb
if __FILE__ == $0
end
```
I create this PR to update the driver code of all the existing Ruby index files at main.
=> chore: Update Ruby driver code

en/CONTRIBUTING.md, en/README.md
- Background requirements for contributors.
- Translation standards.
- Translation priorities of contributors from different linguistic backgrounds.
- Detailed guidance on the translation process.
=> translation: Add the contributing guidelines for Chinese-to-English

en/docs/chapter_graph/index.md
Just changed the words a little. honestly the Machine translation is good already.
=> translation: Update chapter_graph/index.md

docs/chapter_appendix/installation.md, zh-hant/docs/chapter_appendix/installation.md
close https://github.com/krahets/hello-algo/issues/1186
--- 
I'm inclined to remove this line "在 VS Code 的插件市场中搜索 `javascript` ，安装 JavaScript (ES6) code snippets 。" because VS Code already has it built-in.
=> feat(appendix): TypeScript installation

codes/ruby/chapter_tree/array_binary_tree.rb, codes/ruby/chapter_tree/avl_tree.rb, codes/ruby/chapter_tree/binary_search_tree.rb, codes/ruby/chapter_tree/binary_tree.rb, codes/ruby/chapter_tree/binary_tree_bfs.rb, codes/ruby/chapter_tree/binary_tree_dfs.rb, codes/ruby/utils/tree_node.rb
Here is the Ruby code for chapter Tree. Due to the huge size of codes, the code blocks in `.md` files will be in another PR
---
=> feat: Add ruby codes - chapter "Tree"

codes/go/chapter_searching/two_sum.go
=> fix(Golang): Fix incorrect indexes in two_sum.go

codes/ruby/chapter_graph/graph_adjacency_list.rb, codes/ruby/chapter_graph/graph_adjacency_matrix.rb, codes/ruby/chapter_graph/graph_bfs.rb, codes/ruby/chapter_graph/graph_dfs.rb, codes/ruby/utils/print_util.rb, codes/ruby/utils/vertex.rb
=> feat: Add ruby code - chapter "Graph"

mkdocs.yml, overrides/javascripts/mathjax.js
=> Enhance accessibility of MathJax script loading with `cdnjs`

.github/workflows/swift.yml
=> feat: update os and swift

codes/go/chapter_backtracking/permutations_ii.go
Fix incorrect method name in permutations_ii.go
=> Fix incorrect method name in permutations_ii.go

.github/workflows/swift.yml, codes/swift/chapter_array_and_linkedlist/array.swift
=> feat: remove setup-swift

codes/go/chapter_backtracking/n_queens.go
Maintain the same semantics as other languages in n_queens.go
=> Maintain the same semantics as other languages in n_queens.go

codes/ruby/chapter_sorting/bubble_sort.rb, codes/ruby/chapter_sorting/counting_sort.rb, codes/ruby/chapter_sorting/radix_sort.rb, codes/ruby/chapter_sorting/selection_sort.rb
This PR is to finish the rest of chapter Sorting, including:
- Selection sort
- Bubble sort
- Counting sort
- Radix sort
---
=> feat: Add Ruby code - chapter "Sorting"

en/docs/chapter_tree/binary_tree.md
simplified some parts while others added a few words to make it clearer
=> Translation: Update binary_tree.md

codes/rust/chapter_sorting/heap_sort.rs
Will panic in minus operation when array len is less than 2
=> [Rust] Fix panic when array's len is less than 2

codes/rust/chapter_sorting/bubble_sort.rs, codes/rust/chapter_sorting/heap_sort.rs
in select sort we use swap, so we can stick to swap method to swap two value in vector.
=> [Rust] Stick with swap

codes/ruby/chapter_divide_and_conquer/binary_search_recur.rb, codes/ruby/chapter_divide_and_conquer/build_tree.rb, codes/ruby/chapter_divide_and_conquer/hanota.rb
=> feat: Add Ruby code - chapter "Divide and Conquer"

codes/ruby/chapter_backtracking/n_queens.rb, codes/ruby/chapter_backtracking/permutations_i.rb, codes/ruby/chapter_backtracking/permutations_ii.rb, codes/ruby/chapter_backtracking/preorder_traversal_i_compact.rb, codes/ruby/chapter_backtracking/preorder_traversal_ii_compact.rb, codes/ruby/chapter_backtracking/preorder_traversal_iii_compact.rb, codes/ruby/chapter_backtracking/preorder_traversal_iii_template.rb, codes/ruby/chapter_backtracking/subset_sum_i.rb, codes/ruby/chapter_backtracking/subset_sum_i_naive.rb, codes/ruby/chapter_backtracking/subset_sum_ii.rb, docs/chapter_backtracking/backtracking_algorithm.md
=> feat: Add Ruby code - chapter "Backtracking"

docs/chapter_heap/heap.md
---
I have checked all the topics again and seen that we have done the Ruby code transpilation :partying_face: 
Here is the finalized PR for Ruby.
=> Finalize Ruby code transpilation

en/docs/chapter_data_structure/summary.md
The last question in the Chinese version is not found in the initial machine translation. I have added the whole translation on this question.
In Line 10, I use (i)-(iii) to list the benefits of the complement code, because the sentence is too long.
In Line 59, I use the inverse operation of "first negate and then add 1" (the sentence between "" is newly added), to complete the meaning of the sentence.
=> translation: refine the translation of data_structure/summary

en/docs/chapter_graph/index.md
=> translation: refine translation of chapter_graph/index.md

docs/chapter_computational_complexity/time_complexity.md
The variable i does not exist in this code
=> fix invalid code comment

en/docs/chapter_tree/binary_tree.md
=> fix: correct comment translation in binary_tree.md

en/docs/chapter_graph/graph.md
=> translation: refine translation of chapter_graph/graph.md

en/docs/chapter_introduction/algorithms_are_everywhere.md
Fix writing "obsecure" to "obscure"
=> Fix a typo

en/docs/chapter_computational_complexity/time_complexity.md
- [ x ] This PR represents the translation of a single, complete document, or contains only bug fixes.
- [ x ] The translation accurately conveys the original meaning and intent of the Chinese version. If deviations exist, I have provided explanatory comments to clarify the reasons.
=> translation: Refine the first paragraph of Time Complexity

en/docs/chapter_graph/graph_operations.md
=> translation: refine translation of chapter_graph/graph_operations.md

en/docs/chapter_graph/graph_traversal.md
=> translation: refine translation of chapter_graph/graph_traversal.md

en/docs/chapter_tree/binary_search_tree.md
- [*] This PR represents the translation of a single, complete document, or contains only bug fixes.
- [*] The translation accurately conveys the original meaning and intent of the Chinese version. If deviations exist, I have provided explanatory comments to clarify the reasons.
=> translation: refine translation of binary_search_tree.md

en/docs/chapter_tree/index.md
=> doc: translate chapter_tree/index.md to English

codes/csharp/chapter_heap/heap.cs, docs/chapter_heap/heap.md
=> fix(csharp): priority queue comparer initialization

codes/csharp/chapter_dynamic_programming/min_path_sum.cs, codes/dart/chapter_dynamic_programming/min_path_sum.dart, codes/go/chapter_dynamic_programming/min_path_sum_test.go, codes/python/chapter_dynamic_programming/min_path_sum.py, codes/ruby/chapter_dynamic_programming/min_path_sum.rb, codes/swift/chapter_dynamic_programming/min_path_sum.swift
=> fix some typos

en/docs/chapter_searching/index.md
refined some parts of the sentences.
changed 'in' to 'on' as it conveys a sense of movement along a path
=> translation: Update index.md

zh-hant/README.md, zh-hant/docs/index.html
=> Update the links to the zh-hant version of the PDF

en/docs/chapter_graph/summary.md
=> translation: graph summary updates

en/docs/chapter_sorting/heap_sort.md
=> Translation: Update heap_sort.md

en/docs/chapter_sorting/radix_sort.md
=> Translation: Update radix_sort.md

en/docs/chapter_sorting/index.md
=> translation: chapter_sorting/index.md

en/docs/chapter_divide_and_conquer/summary.md
=> translation: Update chapter_divide_and_conquer / summary.md

en/docs/chapter_backtracking/index.md
=> translation: Update chatper_backtracking / index.md

en/docs/chapter_sorting/quick_sort.md
=> Fix the comma in quick_sort.md

en/docs/chapter_sorting/merge_sort.md
=> translate merge_sort.md

en/docs/chapter_divide_and_conquer/hanota_problem.md
=> translation: chapter_divide_and _conquer / Update hanota_problem.md

en/docs/chapter_dynamic_programming/index.md
=> translation: Update chatpter_dynamic_programming / index.md

en/docs/chapter_backtracking/permutations_problem.md
=> tanslation: Update chapter_backtracking / permutations_problem.md

en/docs/chapter_backtracking/backtracking_algorithm.md
=> translation: backtracking algorithm

en/docs/chapter_backtracking/n_queens_problem.md
=> translation: Update n_queens_problem.md

en/docs/chapter_dynamic_programming/intro_to_dynamic_programming.md
=> Translation: Update intro_to_dynamic_programming.md
