krahets/hello-algo

.gitignore
codes/go/chapter_computational_complexity/leetcode_two_sum.go
codes/go/chapter_computational_complexity/leetcode_two_sum_test.go
codes/go/go.mod
docs/chapter_computational_complexity/space_time_tradeoff.md

1.add go code to chapter_computational_complexity

feat(chapter1): add go code to chapter1

---

codes/javascript/chapter_tree/binary_search_tree.js
codes/javascript/chapter_tree/binary_tree.js
codes/javascript/chapter_tree/binary_tree_bfs.js
codes/javascript/chapter_tree/binary_tree_dfs.js
codes/javascript/include/PrintUtil.js
codes/javascript/include/TreeNode.js
docs/chapter_tree/binary_search_tree.md
docs/chapter_tree/binary_tree.md

add JavaScript codes for Tree

---

codes/javascript/chapter_stack_and_queue/array_stack.js
codes/typescript/chapter_stack_and_queue/array_stack.ts
docs/chapter_stack_and_queue/stack.md

Array stack in js and ts

---

codes/go/chapter_computational_complexity/time_complexity_types.go
codes/go/chapter_computational_complexity/time_complexity_types_test.go
codes/go/chapter_computational_complexity/worst_best_time_complexity.go
codes/go/chapter_computational_complexity/worst_best_time_complexity_test.go
docs/chapter_computational_complexity/time_complexity.md

add go code for chapter_computational_complexity/time_complexity.

feat(time-complexity): code implemented in Go

---

codes/go/chapter_computational_complexity/space_complexity.go
codes/go/chapter_computational_complexity/space_complexity_test.go
docs/chapter_computational_complexity/space_complexity.md

feat(space_complexity): add the Go code to space complexity docs (Chapter of Computational Complexity)

Add the Go code to space complexity docs

---

codes/javascript/chapter_searching/binary_search.js
codes/javascript/chapter_searching/linear_search.js
codes/javascript/include/ListNode.js
docs/chapter_searching/binary_search.md
docs/chapter_searching/linear_search.md

I also fixed a error of making assignment to the constant variable in the ListNode.js.

Add JavaScript for linear search

---

codes/javascript/chapter_stack_and_queue/linkedlist_stack.js
codes/typescript/chapter_stack_and_queue/linkedlist_stack.ts
docs/chapter_stack_and_queue/stack.md

- [√] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [√] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [√] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

Update linkedlist stack in JS and TS

---

codes/javascript/chapter_hashing/array_hash_map.js
codes/javascript/chapter_hashing/hash_map.js
docs/chapter_hashing/hash_map.md

Add the JavaScript code and docs for Chapter of Hash Map

---

docs/chapter_tree/binary_search_tree.md

Combining Context, Compare 'cur.val' and 'num', not 'cur.val' and 'val`.

docs(binary_search_tree): variable name error

---

docs/chapter_tree/binary_tree.md

According to the previous annotation style, we should use `/* ... */`.
`二叉树中度的范围是 0, 1, 2 `，修改为 `二叉树中，度的范围是 0, 1, 2`，如果不添加 `，`，会误导读者有一个`中度`的概念。
btw, should the style of punctuation be unified? Full width symbol or half width symbol.

docs(binary_tree): fix comment style and punctuation

---

codes/go/chapter_array_and_linkedlist/array.go
codes/go/chapter_array_and_linkedlist/array_test.go
docs/chapter_array_and_linkedlist/array.md

本次提交包含如下示例代码。
- 遍历数组；
- 初始化数组；
- 扩展数组长度；
- 在数组中查找指定元素；
- 随机返回一个数组元素；
- 删除索引 index 处元素；
- 在数组的索引 index 处插入元素 num。
✅ 已通过测试用例
所有数组约定长度为 5。原因如下：
在 goalng 中，必须声明数组的长度，例如：nums := [5]int{1,2,3,4,5}。如果不声明长度，则被称为切片。
使用的注释没有按照 golang 的编程惯例，而是倾向于使用文档上下文的注释约定。
所以所有函数注释均使用了 `/* ... */`，而不是双斜杠 `//`。

docs(array): sample code for golang

---

codes/cpp/include/PrintUtil.hpp

This fixes clang++ compile error when using INT_MAX in PrintUtil.
- [ Y ] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [ Y ] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [ Y ] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

fix(codes/cpp): add climits headers

---

codes/go/chapter_heap/heap.go
codes/go/chapter_heap/heap_test.go
codes/go/chapter_heap/my_heap.go
codes/go/pkg/print_utils.go
docs/chapter_heap/heap.md

feat(heap): add go codes

---

codes/typescript/chapter_searching/binary_search.ts
docs/chapter_searching/binary_search.md

fix: 二分查找，左闭右开区间实现中，注释区间范围右侧符号应该是)而不应该是]

---

codes/c/chapter_stack_and_queue/array_stack.c

Update array_stack.c codes

---

codes/swift/Package.swift
codes/swift/chapter_searching/binary_search.swift
codes/swift/chapter_searching/hashing_search.swift
codes/swift/chapter_searching/linear_search.swift
codes/swift/utils/ListNode.swift
docs/chapter_searching/binary_search.md
docs/chapter_searching/hashing_search.md
docs/chapter_searching/linear_search.md

feat: add Swift codes for chapter_searching articles

---

codes/c/chapter_stack_and_queue/CMakeLists.txt
codes/c/chapter_stack_and_queue/array_queue.c

Add queue array impl in C

---

codes/swift/Package.swift
codes/swift/chapter_sorting/bubble_sort.swift
codes/swift/chapter_sorting/insertion_sort.swift
codes/swift/chapter_sorting/merge_sort.swift
codes/swift/chapter_sorting/quick_sort.swift
codes/swift/chapter_sorting/radix_sort.swift
docs/chapter_sorting/bubble_sort.md
docs/chapter_sorting/insertion_sort.md
docs/chapter_sorting/merge_sort.md
docs/chapter_sorting/quick_sort.md

feat: add Swift codes for chapter_sorting articles

---

codes/cpp/chapter_heap/heap.cpp
codes/cpp/chapter_heap/my_heap.cpp
codes/cpp/chapter_tree/avl_tree.cpp
docs/chapter_heap/heap.md
docs/chapter_tree/avl_tree.md

- the code was tested. 
- most of them were translated from Java version.
- heap.cpp wasn't translated well, but I have no better idea.

add avl tree and heap part cpp code

---

codes/cpp/chapter_heap/my_heap.cpp
codes/cpp/include/PrintUtil.hpp
docs/chapter_heap/heap.md

✅  I've tested the code and ensured the outputs are the same as the outputs of reference codes.
✅  I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
✅  The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).
我已经完成了my_heap.cpp，实现效果如下：
```C++
输入数组并建堆后
堆的数组表示：
[9, 8, 6, 6, 7, 5, 2, 1, 4, 3, 6, 2]
堆的树状表示：
/——— 2
/——— 6
|    \——— 5
|        \——— 2
——— 9
|        /——— 6
|    /——— 7
|   |    \——— 3
\——— 8
|    /——— 4
\——— 6
\——— 1
堆顶元素为 9
元素 7 入堆后
堆的数组表示：
[9, 8, 7, 6, 7, 6, 2, 1, 4, 3, 6, 2, 5]
堆的树状表示：
/——— 2
/——— 7
|   |    /——— 5
|    \——— 6
|        \——— 2
——— 9
|        /——— 6
|    /——— 7
|   |    \——— 3 …
```

Part Heap : Code Translation into C++ (my_heap.cpp)

---

codes/typescript/chapter_heap/my_heap.ts
codes/typescript/module/PrintUtil.ts
docs/chapter_heap/heap.md

Add TypeScript code and docs to Chapter of Heap

---

codes/rust/chapter_stack_and_queue/deque.rs
codes/rust/chapter_stack_and_queue/queue.rs
codes/rust/include/print_util.rs

I think replacing **LinkedList** with **VecDeque** is more in line with the general usage of the Rust language and more in line with the library of the title.

🦄 refactor(rust/deque):  change LinkedList to VecDeque

---

codes/c/chapter_searching/CMakeLists.txt
codes/c/chapter_searching/binary_search.c
codes/c/chapter_searching/linear_search.c

add C binary_search and linear_search

---

codes/c/chapter_sorting/CMakeLists.txt
codes/c/chapter_sorting/merge_sort.c

feat: add C merge sort

---

codes/javascript/chapter_backtracking/n_queens.js
codes/javascript/chapter_backtracking/permutations_i.js
codes/javascript/chapter_backtracking/permutations_ii.js
codes/typescript/chapter_backtracking/n_queens.ts
codes/typescript/chapter_backtracking/permutations_i.ts
codes/typescript/chapter_backtracking/permutations_ii.ts

Add JavaScript and TypeScript code of permutations and n_queens (Chapter of Backtracking)

---

codes/javascript/chapter_searching/binary_search_edge.js
codes/javascript/chapter_sorting/heap_sort.js
codes/javascript/chapter_sorting/selection_sort.js
codes/typescript/chapter_backtracking/n_queens.ts
codes/typescript/chapter_searching/binary_search_edge.ts
codes/typescript/chapter_sorting/heap_sort.ts
codes/typescript/chapter_sorting/selection_sort.ts

Add JavaScript and TypeScript code of heap sort, selection sort and binary search edge and Fix the indentation of TS code

---

codes/rust/Cargo.toml
codes/rust/chapter_sorting/bucket_sort.rs
codes/rust/chapter_sorting/counting_sort.rs
codes/rust/chapter_sorting/radix_sort.rs

The console outputs of bucket sort:
```
桶排序完成后 nums = [0.09, 0.15, 0.37, 0.43, 0.49, 0.57, 0.75, 0.82, 0.91, 0.96]
```
The console outputs of counting sort:
```
计数排序（无法排序对象）完成后 nums = [0, 0, 0, 1, 1, 2, 2, 2, 4, 4]
计数排序完成后 nums1 = [0, 0, 0, 1, 1, 2, 2, 2, 4, 4]
```
The console outputs of radix sort:
```
基数排序完成后 nums = [10546151, 30524779, 34862445, 35663510, 42865989, 63832996, 72429244, 81883077, 82060337, 88906420]
```

feat: add rust codes for bucket sort, counting sort and radix sort

---

codes/rust/Cargo.toml
codes/rust/chapter_heap/heap.rs
codes/rust/chapter_heap/my_heap.rs
codes/rust/chapter_heap/top_k.rs
codes/rust/include/print_util.rs

Outputs of heap.rs:
```
以下测试样例为大顶堆
元素 1 入堆后
堆的数组表示：[1]
堆的树状表示：
——— 1
元素 3 入堆后
堆的数组表示：[3, 1]
堆的树状表示：
——— 3
\——— 1
元素 2 入堆后
堆的数组表示：[3, 1, 2]
堆的树状表示：
/——— 2
——— 3
\——— 1
元素 5 入堆后
堆的数组表示：[5, 3, 2, 1]
堆的树状表示：
/——— 2
——— 5
\——— 3
\——— 1
元素 4 入堆后
堆的数组表示：[5, 4, 2, 1, 3]
堆的树状表示：
/——— 2
——— 5
|    /——— 3
\——— 4
\——— 1
堆顶元素为 5
堆顶元素 5 出堆后
堆的数组表示：[4, 3, 2, 1]
堆的树状表示：
/——— 2
——— 4
\——— 3
\——— 1
堆顶元素 4 出堆后
堆的数组表示：[3, 1, 2]
堆的树状表示：
/——— 2
——— 3
\——— 1
堆顶元素 3 出堆后
堆的数组表示：[2, 1]
堆的树状表示：
——— 2
\——— 1
堆顶元素 2 出堆后
堆的数组表示：[1]
堆的树状表示：
——— 1
堆顶元素 1 出堆后
堆的数组表示：[]
堆的树状表示：
堆元素数量为 0
堆是否为空 true
输入列表并建立小顶堆后
堆的数组表示：[1, 3, 2, 5, 4]
堆的树状表示：
/——— 2
——— 1
|    /——— 4
\——— 3
\——— 5
```
Outputs of …

feat: add rust codes for chapter heap

---

codes/rust/Cargo.toml
codes/rust/chapter_divide_and_conquer/binary_search_recur.rs
codes/rust/chapter_divide_and_conquer/build_tree.rs
codes/rust/chapter_divide_and_conquer/hanota.rs

@krahets  Hi. All the codes outpus are the same with Java codes.
- commit 1 => rust : add codes for chapter_divide_and_conquer.

rust : add codes for chapter_divide_and_conquer

---

codes/csharp/chapter_tree/array_binary_tree.cs
codes/csharp/utils/PrintUtil.cs
codes/csharp/utils/TreeNode.cs

1. add code for array binary tree
2. rewrite utils/TreeNode.cs
3. add extension method for print nullable list 
Test result:

feat(csharp): add csharp code for array binary tree

---

codes/javascript/chapter_tree/array_binary_tree.js
codes/javascript/modules/TreeNode.js
codes/typescript/chapter_tree/array_binary_tree.ts
codes/typescript/modules/TreeNode.ts

feat(tree): Add the array representation of the binary tree(js,ts)

---

codes/dart/chapter_computational_complexity/iteration.dart
codes/dart/chapter_computational_complexity/recursion.dart

feat: Add Dart Codes for section_iteration_and_recursion

---

codes/rust/Cargo.toml
codes/rust/chapter_searching/binary_search_edge.rs
codes/rust/chapter_searching/binary_search_insertion.rs

The output of `binary_search_insertion.rs`:
```
数组 nums = [1, 3, 6, 8, 12, 15, 23, 26, 31, 35]
元素 6 的插入点的索引为 2
元素 9 的插入点的索引为 4
数组 nums = [1, 3, 6, 6, 6, 6, 6, 10, 12, 15]
元素 2 的插入点的索引为 1
元素 6 的插入点的索引为 2
元素 20 的插入点的索引为 10
```
The output of `binary_search_edge.rs`:
```
数组 nums = [1, 3, 6, 6, 6, 6, 6, 10, 12, 15]
最左一个元素 6 的索引为 2
最右一个元素 6 的索引为 6
最左一个元素 7 的索引为 -1
最右一个元素 7 的索引为 -1
```

Feat: add rust codes for chapter searching

---

codes/go/chapter_dynamic_programming/min_cost_climbing_stairs_dp.go

- This pull request addresses an issue and fixes it by correctly updating the state transition in the `minCostClimbingStairsDP` and `minCostClimbingStairsDPComp` function.
- In the `minCostClimbingStairsDP` function, the previous implementation had an error in the state transition logic where it was incorrectly choosing to `int(math.Min(float64(dp[i-1]), float64(dp[i-2]+cost[i])))` instead of `int(math.Min(float64(dp[i-1]+cost[i]), float64(dp[i-2]+cost[i])))`. In order to improve readability, I have adopted the following approach and implemented the `min` function: `min(dp[i-1], dp[i-2]) + cost[i]`.
- For the `minCostClimbingStairsDPComp` function, the modification is the same as above.

fix: Fixed the state transition error in minCostClimbingStairsDP and minCostClimbingStairsDPComp function

---

docs/chapter_array_and_linkedlist/list.md

Python 代码中的列表命名为list时，会出现如下错误。
list:list[int] = [1, 2, 3, 4, 5]
TypeError: list indices must be integers or slices, not type 建议修改为list2

fix a Python variable name in list.md

---

codes/c/chapter_heap/CMakeLists.txt
codes/c/chapter_heap/my_heap.c
codes/c/chapter_heap/my_heap_test.c
codes/c/chapter_heap/top_k.c
codes/cpp/chapter_heap/top_k.cpp
codes/csharp/chapter_heap/top_k.cs
codes/dart/chapter_heap/top_k.dart
codes/go/chapter_heap/top_k.go
codes/java/chapter_heap/top_k.java
codes/javascript/chapter_heap/my_heap.js
codes/javascript/chapter_heap/top_k.js
codes/python/chapter_heap/top_k.py
codes/rust/chapter_heap/top_k.rs

feat: add top_k.c and refactor top_k.js

---

codes/c/chapter_sorting/merge_sort.c
codes/cpp/chapter_sorting/merge_sort.cpp
codes/csharp/chapter_sorting/merge_sort.cs
codes/go/chapter_sorting/merge_sort.go
codes/java/chapter_sorting/merge_sort.java
codes/javascript/chapter_sorting/merge_sort.js
codes/python/chapter_sorting/merge_sort.py
codes/typescript/chapter_sorting/merge_sort.ts

refactor: Re-implement merge sort function.

---

codes/swift/Package.resolved
codes/swift/Package.swift
codes/swift/chapter_heap/top_k.swift
codes/swift/chapter_sorting/merge_sort.swift

feature(swift): Reimplement merge_sort and top_k 

---

docs-en/chapter_appendix/terminology.md

fix: Fix EN translation of chapter_appendix/terminology.md

---

README.md
docs-en/index.md
mkdocs-en.yml

* Synced README.md with the Chinese version
* Changed a few wording 
A small note: I've removed the line breaks before the `</a>` labels to fix a known render issue:
```
<p align="center">
<a href="https://www.hello-algo.com/">
<a href="https://github.com/krahets/hello-algo/releases">
</p>
```
The previous format is causing render issue for Chromium-based browsers:

translation: Refined the automated translation of README

---

codes/dart/chapter_array_and_linkedlist/array.dart
codes/dart/chapter_array_and_linkedlist/list.dart
codes/dart/chapter_array_and_linkedlist/my_list.dart
codes/dart/chapter_computational_complexity/time_complexity.dart
codes/dart/chapter_hashing/built_in_hash.dart
codes/dart/chapter_sorting/bucket_sort.dart
codes/dart/chapter_sorting/counting_sort.dart
codes/dart/chapter_sorting/radix_sort.dart
codes/dart/chapter_stack_and_queue/array_deque.dart
codes/dart/chapter_stack_and_queue/array_queue.dart
codes/dart/chapter_stack_and_queue/array_stack.dart
codes/dart/chapter_stack_and_queue/linkedlist_deque.dart
codes/dart/chapter_stack_and_queue/linkedlist_queue.dart
codes/dart/chapter_stack_and_queue/linkedlist_stack.dart
codes/dart/chapter_tree/binary_search_tree.dart

fix(Dart): Avoid using num as a variable name

---

codes/c/chapter_array_and_linkedlist/array.c
codes/c/chapter_backtracking/preorder_traversal_i_compact.c
codes/c/chapter_backtracking/preorder_traversal_ii_compact.c
codes/c/chapter_backtracking/preorder_traversal_iii_compact.c
codes/c/chapter_backtracking/preorder_traversal_iii_template.c
codes/c/chapter_dynamic_programming/climbing_stairs_constraint_dp.c
codes/c/chapter_dynamic_programming/coin_change.c
codes/c/chapter_dynamic_programming/coin_change_ii.c
codes/c/chapter_dynamic_programming/edit_distance.c
codes/c/chapter_dynamic_programming/knapsack.c
codes/c/chapter_dynamic_programming/min_cost_climbing_stairs_dp.c
codes/c/chapter_dynamic_programming/min_path_sum.c
codes/c/chapter_dynamic_programming/unbounded_knapsack.c
codes/c/chapter_greedy/CMakeLists.txt
codes/c/chapter_greedy/max_capacity.c
codes/c/chapter_heap/top_k.c
codes/c/chapter_stack_and_queue/array_deque.c
codes/c/chapter_stack_and_queue/array_queue.c
codes/c/chapter_stack_and_queue/linkedlist_deque.c
codes/c/chapter_stack_and_queue/linkedlist_queue.c
codes/c/utils/print_util.h
codes/cpp/chapter_backtracking/preorder_traversal_i_compact.cpp
codes/cpp/chapter_backtracking/preorder_traversal_ii_compact.cpp

Avoid Variable-Length Arrays (VLAs): MSVC does not support VLAs. Instead, use dynamic memory allocation or fixed-size arrays.

fix: Update C code for compatibility with the MSVC compiler

---

codes/java/chapter_tree/array_binary_tree.java

Java代码中，字符串内容的比较需要使用equals方法，'=='比较的是两个对象的地址是否相等。

fix: Use .equals() to compare two strings in Java

---

docs-en/chapter_preface/summary.md

This commit made a few adjustments in the 'summary.md' file for clearer and more accessible language. "Brushing tool library" was replaced with "Coding Toolkit" to better reflect common terminology. Also, advice for beginners in algorithm learning journey was reformulated to imply a more positive approach avoiding detours and common pitfalls. The section related to the discussion forum was rewritten to sound more inviting to readers.

translation: Update terminology and improve readability in preface summary

---

codes/swift/chapter_array_and_linkedlist/array.swift

文章中的插入删除操作，完全没必要用sequence。无论是性能，还是直观简便性上。对读者不友好建议换掉

Simplify the code in array.swift

---

codes/c/chapter_sorting/bubble_sort.c

fix(codes/c): Fix bubble_sort.c

---

docs-en/chapter_introduction/what_is_dsa.md

translation: chapter_introduction/what_is_dsa.md

---

docs-en/chapter_introduction/summary.md

translation: chapter_introduction/summary.md

---

docs-en/chapter_data_structure/classification_of_data_structure.md

translation: Update chapter_data_structure/classification_of_data_structure.md

---

docs-en/chapter_introduction/algorithms_are_everywhere.md

changed or refined parts of the words and sentences including tips. Some of them I didnt change that much because im worried that it might not meet the requirement of accuracy.  some other ones i changed a lot to make it sound better, but also kind of following the same wording as the CN version

translation: Update chapter_introduction/algorithms_are_everywhere.md

---

docs-en/chapter_data_structure/number_encoding.md

translation: Update chapter_data_structure/number_encoding.md

---

docs-en/chapter_array_and_linkedlist/index.md

translation: Update index.md

---

docs-en/chapter_array_and_linkedlist/array.md

refined some parts, some changed up a bit.

translation: Update array.md

---

codes/cpp/chapter_stack_and_queue/linkedlist_deque.cpp

There is something error when delete node, should 'delete front' or 'delete rear' outside the body of if cycle.

fix: Update linkedlist_deque.cpp

---

docs-en/chapter_data_structure/character_encoding.md

translation: Update chapter_data_structure/character_encoding.md

---

docs-en/chapter_stack_and_queue/summary.md

translation: Update chapter_stack_and_queue/summary.md

---

docs-en/chapter_array_and_linkedlist/linked_list.md

translation: Updated chapter_array_and_linkedlist/linked_list.md

---

codes/cpp/chapter_sorting/quick_sort.cpp

Fix the driver code of quick_sort.cpp

---

codes/c/chapter_hashing/hash_map_open_addressing.c
codes/c/chapter_stack_and_queue/linkedlist_deque.c

Compared to the C++ version, I think this C version of 'pop' cannot free the popped-out node correctly when it's the only one remains in the queue. This PR fix this and make it consistent with the C++ version.

fix memory leak in the C code

---

codes/rust/chapter_hashing/hash_map_chaining.rs
codes/rust/chapter_tree/binary_tree_bfs.rs
codes/rust/chapter_tree/binary_tree_dfs.rs
codes/rust/include/tree_node.rs

in this fn:
`    fn put(&mut self, key: i32, val: String) `
as you can see from the method signature val is owned by this method, so there's no need to clone to put in hash bucket.
and fmt some code to drop unseen space, but it shows in my editor:

fix(Rust): no need to clone in hash put fn

---

codes/ruby/chapter_stack_and_queue/array_deque.rb
codes/ruby/chapter_stack_and_queue/array_queue.rb
codes/ruby/chapter_stack_and_queue/array_stack.rb
codes/ruby/chapter_stack_and_queue/deque.rb
codes/ruby/chapter_stack_and_queue/linkedlist_deque.rb
codes/ruby/chapter_stack_and_queue/linkedlist_queue.rb
codes/ruby/chapter_stack_and_queue/linkedlist_stack.rb
codes/ruby/chapter_stack_and_queue/queue.rb
codes/ruby/chapter_stack_and_queue/stack.rb

> Due to the huge load of code, the Ruby code blocks of .md files for this chapter will be in another PR.
---
---

feat: Add Ruby code - chapter "Stack & Queue"

---

codes/kotlin/chapter_divide_and_conquer/build_tree.kt
codes/kotlin/chapter_divide_and_conquer/hanota.kt
codes/kotlin/chapter_dynamic_programming/climbing_stairs_backtrack.kt
codes/kotlin/chapter_dynamic_programming/climbing_stairs_dfs_mem.kt
codes/kotlin/chapter_dynamic_programming/climbing_stairs_dp.kt
codes/kotlin/chapter_dynamic_programming/coin_change.kt
codes/kotlin/chapter_dynamic_programming/edit_distance.kt
codes/kotlin/chapter_dynamic_programming/knapsack.kt
codes/kotlin/chapter_dynamic_programming/min_cost_climbing_stairs_dp.kt
codes/kotlin/chapter_dynamic_programming/min_path_sum.kt
codes/kotlin/chapter_dynamic_programming/unbounded_knapsack.kt
codes/kotlin/chapter_graph/graph_adjacency_list.kt
codes/kotlin/chapter_graph/graph_adjacency_matrix.kt
codes/kotlin/chapter_graph/graph_bfs.kt
codes/kotlin/chapter_graph/graph_dfs.kt

Improve readability of kotlin code

---

docs/chapter_stack_and_queue/deque.md
docs/chapter_stack_and_queue/queue.md
docs/chapter_stack_and_queue/stack.md

I create this PR for the .md files update of chapter "Stack & Queue"

feat: Add ruby code blocks - chapter "Stack & Queue"

---

codes/c/chapter_dynamic_programming/coin_change.c

fix(C): fix the array initialization in coin_change.c 

---

codes/c/utils/common.h

一个非常小的建议，请问这里为了防止重复包含头文件是不是应该改成COMMON_H，因为头文件名字叫做common.h

fix(C): Update common.h

---

codes/ruby/chapter_hashing/array_hash_map.rb
codes/ruby/chapter_hashing/built_in_hash.rb
codes/ruby/chapter_hashing/hash_map.rb
codes/ruby/chapter_hashing/hash_map_chaining.rb
codes/ruby/chapter_hashing/hash_map_open_addressing.rb
codes/ruby/chapter_hashing/simple_hash.rb
codes/ruby/utils/print_util.rb
docs/chapter_hashing/hash_algorithm.md
docs/chapter_hashing/hash_map.md

feat: Add Ruby code - chapter "Hashing"

---

.github/workflows/javascript.yml
codes/javascript/chapter_array_and_linkedlist/array.js
codes/javascript/test_all.js
codes/javascript/test_all.ts

feat(JavaScript): Add the workflow file for CI check

---

codes/rust/chapter_heap/my_heap.rs

First I find here using pop is better than remove, but I'm hesitate to create a PR for this(in case some inconsistent) until I found cpp is using pop_back() too. so here I am :)

fix(Rust): Update my_heap.rs

---

codes/ruby/chapter_sorting/heap_sort.rb

feat: add ruby code block - heap sort 

---

codes/ruby/chapter_sorting/merge_sort.rb

feat: add ruby code block - merge sort

---

codes/ruby/chapter_greedy/coin_change_greedy.rb
codes/ruby/chapter_greedy/fractional_knapsack.rb
codes/ruby/chapter_greedy/max_capacity.rb
codes/ruby/chapter_greedy/max_product_cutting.rb

feat: Add Ruby codes - chapter "Greedy"

---

codes/rust/chapter_sorting/bucket_sort.rs
codes/rust/chapter_sorting/counting_sort.rs

there's no need to use mut iter, just iter is enough

[Rust] No need to use mut iter

---

codes/rust/chapter_array_and_linkedlist/array.rs
codes/rust/chapter_backtracking/preorder_traversal_i_compact.rs
codes/rust/chapter_backtracking/preorder_traversal_ii_compact.rs
codes/rust/chapter_backtracking/preorder_traversal_iii_compact.rs
codes/rust/chapter_backtracking/preorder_traversal_iii_template.rs

1. current main's backtrack template: ./target/debug/preorder_traversal_iii_template will panic.
2. some improvement, sorry for not fixing this in one PR, just reading through rust code chapter by chapter.

[Rust] make rust part more idomatic and fix panic of backtrack template

---

codes/ruby/chapter_dynamic_programming/climbing_stairs_backtrack.rb
codes/ruby/chapter_dynamic_programming/climbing_stairs_constraint_dp.rb
codes/ruby/chapter_dynamic_programming/climbing_stairs_dfs.rb
codes/ruby/chapter_dynamic_programming/climbing_stairs_dfs_mem.rb
codes/ruby/chapter_dynamic_programming/climbing_stairs_dp.rb
codes/ruby/chapter_dynamic_programming/coin_change.rb
codes/ruby/chapter_dynamic_programming/coin_change_ii.rb
codes/ruby/chapter_dynamic_programming/edit_distance.rb
codes/ruby/chapter_dynamic_programming/knapsack.rb
codes/ruby/chapter_dynamic_programming/min_cost_climbing_stairs_dp.rb
codes/ruby/chapter_dynamic_programming/min_path_sum.rb
codes/ruby/chapter_dynamic_programming/unbounded_knapsack.rb

[feat] Add Ruby code - chapter "Dynamic Programming"

---

codes/rust/chapter_computational_complexity/time_complexity.rs

There is no need to use `as` to convert the type of ignored value.

Rust: remove unnecessary type conversions

---

en/docs/chapter_tree/avl_tree.md

Fix translation mistake of "先左旋後右旋" from "Right-left" to "Left-right" and "先右旋後左旋" from "Left-right" to "Right-left" on the AVL tree page.

fix: right-left and left-right inversion for the English version of AVL Tree

---

codes/cpp/chapter_sorting/quick_sort.cpp

[cpp] Stick with swap

---

codes/rust/chapter_backtracking/n_queens.rs
codes/rust/chapter_backtracking/subset_sum_i.rs
codes/rust/chapter_backtracking/subset_sum_i_naive.rs
codes/rust/chapter_backtracking/subset_sum_ii.rs

idiomatic rust

---

en/docs/chapter_tree/binary_tree_traversal.md

doc: translate chapter_tree/binary_tree_traversal.md

---

codes/rust/chapter_tree/array_binary_tree.rs
codes/rust/chapter_tree/binary_search_tree.rs
codes/rust/chapter_tree/binary_tree_dfs.rs

make dfs same as c/c++ and other small improvement

---

codes/c/chapter_searching/two_sum.c
codes/c/chapter_sorting/counting_sort.c
codes/c/chapter_sorting/radix_sort.c

* Use a pointer to a pointer instead of a single pointer in the insert function, ensuring proper updates to the hash table
* Bug fixes: This fixes issues with empty results.

fix(lang: c, chapters: searching, sorting): Some serious errors

---

en/docs/chapter_tree/binary_tree.md

translation: chapter_tree/binary_tree.md

---

en/docs/chapter_searching/binary_search.md

translation: binary search updates

---

codes/c/chapter_stack_and_queue/array_deque.c
codes/c/chapter_stack_and_queue/array_queue.c

Fix the function for printing the queue

---

codes/go/chapter_sorting/bubble_sort_test.go
zh-hant/codes/go/chapter_sorting/bubble_sort_test.go

fix(bubble-sort): update incorrect variable name in test output

---

codes/rust/chapter_array_and_linkedlist/array.rs
codes/rust/chapter_array_and_linkedlist/linked_list.rs
codes/rust/src/include/vertex.rs

rust linked_list update
1. in remove, the if let check already exclude the None case, so no need in rust
2. in find, the third argument is only show in rust, the signature should be API level equivalence. hide this in inner function.
happy 2025!

fix rust linked list

---

en/docs/chapter_sorting/sorting_algorithm.md

translation: optimized translation of sorting/sorting_algorithm.md

---

codes/python/chapter_stack_and_queue/linkedlist_deque.py

According to [PEP 8](https://peps.python.org/pep-0008/#programming-recommendations), "Comparisons to singletons like None should always be done with is or is not, never the equality operators."

Fix python code style issue in linked list deque

---

en/docs/chapter_searching/searching_algorithm_revisited.md

translation: update searching_algorithm_revisited.md 

---

en/docs/chapter_computational_complexity/performance_evaluation.md

I've added some parts to align with the Chinese version and rephrased certain sentences for better readability. I personally prefer the term 'Practical Testing' over 'Actual Testing' because it is more commonly used and more relevant to the content. However, I'm not certain about the definitive correct term, so didn’t make the change.

translation: Update chapter_computational_complexity/performance_evaluation.md

---

codes/rust/chapter_hashing/hash_map_chaining.rs

replace replace with take according to clippy suggestion

---

en/docs/chapter_heap/index.md

translation: update heap index translation

---

en/docs/chapter_heap/heap.md

translation: Update heap.md

---

codes/rust/chapter_array_and_linkedlist/my_list.rs
codes/rust/chapter_stack_and_queue/linkedlist_deque.rs
codes/rust/chapter_stack_and_queue/linkedlist_queue.rs
codes/rust/chapter_stack_and_queue/linkedlist_stack.rs

small fix, see PR comment for detail

idomatic rust

---

en/docs/chapter_sorting/selection_sort.md

translation: optimize translation for selection sort

---

en/docs/chapter_sorting/bucket_sort.md

translation: update bucket sort translation

---

en/docs/chapter_sorting/insertion_sort.md

translation: update insertion_sort.md

---

codes/javascript/chapter_hashing/simple_hash.js
codes/typescript/chapter_hashing/simple_hash.ts

The bitwise AND operation does not ensure that the hash value is within an appropriate range. According to the docs, a modulo operation is required here.
Implementations in some other languages ​​have the same issue.

fix: update the implementation of simple_hash.js and .ts

---

en/docs/chapter_sorting/counting_sort.md

translation: update counting_sort.md

---

en/docs/chapter_sorting/bubble_sort.md

translation: Update chapter_sorting / bubble_sort.md

---

codes/python/chapter_sorting/counting_sort.py

Since the `max` function is called to find the maximum value, it doesn't seem necessary to traverse the list and call the `max` function several times to select the larger value.

Improve the efficiency of function call

---

codes/javascript/chapter_sorting/counting_sort.js
codes/javascript/chapter_sorting/radix_sort.js
codes/typescript/chapter_sorting/counting_sort.ts
codes/typescript/chapter_sorting/radix_sort.ts

program output
```shell
计数排序（无法排序对象）完成后 nums = [ 0, 0, 0, 1, 1, 2, 2, 2, 4, 4 ]
计数排序完成后 nums1 = [ 0, 0, 0, 1, 1, 2, 2, 2, 4, 4 ]
```

optimized the js api use of counting_sort chapter for Math.max()

---

codes/javascript/chapter_graph/graph_adjacency_list.js
codes/typescript/chapter_graph/graph_adjacency_list.ts
zh-hant/codes/javascript/chapter_graph/graph_adjacency_list.js
zh-hant/codes/typescript/chapter_graph/graph_adjacency_list.ts

9.2.2 基于邻接表的实现中 JS 和 TS 代码片段 `removeEdge` 函数如果传入的两个顶点不为邻接点，那么在对应邻接表 `adjList` 中查找不到对应的顶点，返回 -1，继续执行则会删除顶点的邻接顶点表最后一项，即 `splice(-1, 1)`。
通过添加边界条件判断两顶点是否为邻接点修复此问题。
相关代码控制台输出：
```js
初始化后，图为
邻接表 =
1: 3,5
3: 1,2
2: 3,5,4
5: 2,1,4
4: 2,5
添加边 1-2 后，图为
邻接表 =
1: 3,5,2
3: 1,2
2: 3,5,4,1
5: 2,1,4
4: 2,5
删除边 1-3 后，图为
邻接表 =
1: 5,2
3: 2
2: 3,5,4,1
5: 2,1,4
4: 2,5
添加顶点 6 后，图为
邻接表 =
1: 5,2
3: 2
2: 3,5,4,1
5: 2,1,4
4: 2,5
6:
删除顶点 3 后，图为
邻接表 =
1: 5,2
2: 5,4,1
5: 2,1,4
4: …
```

fix(graph): enhance the judgment of corner case for removeEdge functions

---

en/docs/chapter_introduction/algorithms_are_everywhere.md
en/docs/chapter_introduction/summary.md
en/docs/chapter_introduction/what_is_dsa.md

translation: Update EN translation for Introduction Chapter

---

codes/c/chapter_greedy/max_capacity.c

greedy/max_capacity: fix myMax algorithm error

---

codes/rust/chapter_graph/graph_adjacency_list.rs
codes/rust/chapter_graph/graph_adjacency_matrix.rs
codes/rust/chapter_graph/graph_bfs.rs

polish rust

---

en/docs/chapter_data_structure/classification_of_data_structure.md

---
- `Line 11`: Missing sentence `，元素之间是一对一的顺序关系`.
- `Line 33`: Improve grammar and sentence structure
- More straightforward and easier to read.
- Correct Subject-verb agreement (`memory resources` &rarr; `are`).
- Maintain the formal tone but increase natural tone to improve fluency.
- Emphasize `memory resources` is the key factor.
- `important` sounds less dramatic than `crucial`.
- `Line 48`: Added hyperlink to the next chapter for easier access.
- `Line 11`: 补充溜掉翻译 `，元素之间是一对一的顺序关系`。
- `Line 33`： 改善文法和句子结构
- 更直接，更容易阅读。
- 改正动词（`memory resources`在英语里是众数，所以因该用`are`）。
- 保持正式语气，但增加自然语气 &mdash; 改善流畅。
- 强调 ⌈内存资源⌋ 是关键因素。
- …

translation: Update `chapter_data_structure/classification_of_data_structure.md`
